export const classic = [
    { option1: 'Ser invisible', option1Votes: 0, option2: 'Ser capaz de volar', option2Votes: 0 },
    { option1: 'Ser rico', option1Votes: 0, option2: 'Ser famoso', option2Votes: 0 },
    { option1: 'Ser el mejor amigo de un famoso', option1Votes: 0, option2: 'Ser el peor enemigo de un famoso', option2Votes: 0 },
    { option1: 'Ser el mejor en algo que no te gusta', option1Votes: 0, option2: 'Ser el peor en algo que te gusta', option2Votes: 0 },
    { option1: 'Tener el poder de leer mentes', option1Votes: 0, option2: 'Tener el poder de ser invisible', option2Votes: 0 },
    { option1: 'Ser millonario pero siempre trabajar', option1Votes: 0, option2: 'Ser pobre pero nunca tener que trabajar', option2Votes: 0 },
    { option1: 'Viajar al pasado', option1Votes: 0, option2: 'Viajar al futuro', option2Votes: 0 },
    { option1: 'Ser extremadamente inteligente pero no tener sentido del humor', option1Votes: 0, option2: 'Ser muy divertido pero no ser muy inteligente', option2Votes: 0 },
    { option1: 'Tener la capacidad de volverse invisible cuando nadie te esté mirando', option1Votes: 0, option2: 'Tener la capacidad de volar pero solo a una altura máxima de 1 metro', option2Votes: 0 },
    { option1: 'Ser siempre el centro de atención', option1Votes: 0, option2: 'Pasar desapercibido en cualquier situación', option2Votes: 0 },
    { option1: 'Tener la capacidad de controlar el clima', option1Votes: 0, option2: 'Tener la capacidad de hablar con los animales', option2Votes: 0 },
    { option1: 'Ser extremadamente rico pero nunca encontrar el amor verdadero', option1Votes: 0, option2: 'Encontrar el amor verdadero pero siempre tener problemas financieros', option2Votes: 0 },
    { option1: 'Ser conocido por algo negativo pero ser millonario', option1Votes: 0, option2: 'Ser desconocido pero amado por todos', option2Votes: 0 },
    { option1: 'Poder leer todos los libros del mundo en un instante', option1Votes: 0, option2: 'Poder hablar todos los idiomas del mundo de forma fluida', option2Votes: 0 },
    { option1: 'Tener la capacidad de detener el tiempo', option1Votes: 0, option2: 'Tener la capacidad de viajar en el tiempo', option2Votes: 0 },
    { option1: 'Ser el mejor en tu profesión pero odiar lo que haces', option1Votes: 0, option2: 'Hacer lo que amas pero no ser reconocido por ello', option2Votes: 0 },
    { option1: 'Tener la capacidad de controlar los sueños', option1Votes: 0, option2: 'Tener la capacidad de cambiar el pasado', option2Votes: 0 },
    { option1: 'Ser un genio incomprendido', option1Votes: 0, option2: 'Ser una persona promedio pero muy feliz', option2Votes: 0 },
    { option1: 'Ser teletransportado instantáneamente a cualquier lugar', option1Votes: 0, option2: 'Tener la capacidad de leer la mente de las personas', option2Votes: 0 },
    { option1: 'Tener la capacidad de hablar con los animales', option1Votes: 0, option2: 'Tener la capacidad de hablar todos los idiomas humanos', option2Votes: 0 },
    { option1: 'Ser capaz de ver 10 minutos en el futuro', option1Votes: 0, option2: 'Ser capaz de ver 150 años en el futuro', option2Votes: 0 },
    { option1: 'Ser el mejor jugador de videojuegos del mundo', option1Votes: 0, option2: 'Ser el mejor deportista en tu deporte favorito', option2Votes: 0 },
    { option1: 'Tener la capacidad de detener el envejecimiento', option1Votes: 0, option2: 'Tener la capacidad de curar cualquier enfermedad', option2Votes: 0 },
    { option1: 'Tener la capacidad de teletransportarte a cualquier lugar del mundo', option1Votes: 0, option2: 'Tener la capacidad de viajar en el tiempo', option2Votes: 0 },
    { option1: 'Ser un experto en todas las artes marciales', option1Votes: 0, option2: 'Ser un maestro en todas las disciplinas musicales', option2Votes: 0 },
    { option1: 'Tener la capacidad de comunicarte con los seres extraterrestres', option1Votes: 0, option2: 'Tener la capacidad de explorar los océanos más profundos', option2Votes: 0 },
    { option1: 'Tener la capacidad de controlar los elementos naturales (agua, fuego, aire, tierra)', option1Votes: 0, option2: 'Tener la capacidad de controlar las mentes de las personas', option2Votes: 0 },
    { option1: 'Ser el personaje principal de tu videojuego favorito', option1Votes: 0, option2: 'Vivir en el mundo real pero con la capacidad de usar poderes mágicos', option2Votes: 0 },
    { option1: 'Tener la capacidad de viajar instantáneamente a cualquier libro y experimentar su historia', option1Votes: 0, option2: 'Tener la capacidad de crear tus propias historias con solo pensarlo', option2Votes: 0 },
    { option1: 'Tener la capacidad de leer todos los libros del mundo en un instante', option1Votes: 0, option2: 'Tener la capacidad de absorber todo el conocimiento del mundo con solo tocar un objeto', option2Votes: 0 },
    { option1: 'Ser invisible pero hacer un sonido fuerte cada vez que te mueves', option1Votes: 0, option2: 'Ser capaz de volar pero solo a baja velocidad', option2Votes: 0 },
    { option1: 'Ser el mejor chef del mundo', option1Votes: 0, option2: 'Ser el mejor músico del mundo', option2Votes: 0 },
    { option1: 'Tener la capacidad de predecir el futuro', option1Votes: 0, option2: 'Tener la capacidad de cambiar el pasado', option2Votes: 0 },
    { option1: 'Ser inmune a todas las enfermedades', option1Votes: 0, option2: 'Tener una increíble resistencia física', option2Votes: 0 },
    { option1: 'Ser capaz de entender y hablar con las plantas', option1Votes: 0, option2: 'Ser capaz de comunicarte con los animales', option2Votes: 0 },
    { option1: 'Tener la capacidad de controlar y manipular el clima', option1Votes: 0, option2: 'Tener la capacidad de controlar y manipular los sueños', option2Votes: 0 },
    { option1: 'Tener la capacidad de teletransportarte a cualquier lugar del pasado', option1Votes: 0, option2: 'Tener la capacidad de teletransportarte a cualquier lugar del futuro', option2Votes: 0 },
    { option1: 'Tener la capacidad de regresar en el tiempo y corregir tus errores', option1Votes: 0, option2: 'Tener la capacidad de ver el futuro y saber qué decisiones tomar', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer realidad cualquier deseo tuyo', option1Votes: 0, option2: 'Tener la capacidad de hacer realidad cualquier deseo de los demás', option2Votes: 0 },
    { option1: 'Ser conocido por haber descubierto una cura para una enfermedad mortal', option1Votes: 0, option2: 'Ser conocido por haber inventado una tecnología revolucionaria', option2Votes: 0 },
    { option1: 'Siempre tener que hablar en rima', option1Votes: 0, option2: 'Siempre tener que cantar lo que dices', option2Votes: 0 },
    { option1: 'Siempre tener que moverte como un robot', option1Votes: 0, option2: 'Siempre tener que moverte como un animal', option2Votes: 0 },
    { option1: 'Tener siempre una melodía pegajosa en la cabeza', option1Votes: 0, option2: 'Nunca más poder escuchar música', option2Votes: 0 },
    { option1: 'Siempre sentirte demasiado caliente', option1Votes: 0, option2: 'Siempre sentirte demasiado frío', option2Votes: 0 },
    { option1: 'Tener una conversación solo en memes', option1Votes: 0, option2: 'Tener una conversación solo en emojis', option2Votes: 0 },
    { option1: 'Siempre tener que contar chistes malos', option1Votes: 0, option2: 'Nunca más poder escuchar un chiste', option2Votes: 0 },
    { option1: 'Tener una mascota dinosaurio', option1Votes: 0, option2: 'Tener una mascota dragón', option2Votes: 0 },
    { option1: 'Siempre tener que bailar cuando escuchas música', option1Votes: 0, option2: 'Siempre tener que hacer muecas cuando hablas', option2Votes: 0 },
    { option1: 'Tener la capacidad de hablar con los objetos inanimados', option1Votes: 0, option2: 'Tener la capacidad de entender el lenguaje de las abejas', option2Votes: 0 },
    { option1: 'Tener un guardaespaldas unicornio', option1Votes: 0, option2: 'Tener un guardaespaldas ninja', option2Votes: 0 },
    { option1: 'Siempre tener que andar en bicicleta para moverte', option1Votes: 0, option2: 'Siempre tener que saltar como un canguro para moverte', option2Votes: 0 },
    { option1: 'Tener un clon de ti que haga todas las tareas aburridas', option1Votes: 0, option2: 'Tener un clon de ti que te siga y repita todo lo que haces', option2Votes: 0 },
    { option1: 'Siempre tener un fondo musical en tu vida', option1Votes: 0, option2: 'Siempre tener una audiencia que aplaude después de cada cosa que haces', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender el lenguaje de los bebés', option1Votes: 0, option2: 'Tener la capacidad de comunicarte con los animales', option2Votes: 0 },
    { option1: 'Tener un teléfono que solo pueda enviar gifs', option1Votes: 0, option2: 'Tener un teléfono que solo pueda enviar memes', option2Votes: 0 },
    { option1: 'Siempre tener que usar un sombrero extravagante', option1Votes: 0, option2: 'Siempre tener que usar zapatos que suenan con cada paso', option2Votes: 0 },
    { option1: 'Siempre tener que reemplazar cada palabra con "meow"', option1Votes: 0, option2: 'Siempre tener que reemplazar cada palabra con "quack"', option2Votes: 0 },
    { option1: 'Tener la capacidad de cambiar de color como un camaleón', option1Votes: 0, option2: 'Tener la capacidad de brillar en la oscuridad como una luciérnaga', option2Votes: 0 },
    { option1: 'Siempre tener que moverte haciendo moonwalk', option1Votes: 0, option2: 'Siempre tener que moverte como si estuvieras en una pasarela', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender los pensamientos de los gatos', option1Votes: 0, option2: 'Tener la capacidad de entender los pensamientos de los perros', option2Votes: 0 },
    { option1: 'Siempre tener una canción de fondo cuando hablas', option1Votes: 0, option2: 'Nunca más poder escuchar tu voz', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer preguntas divertidas a las personas', option1Votes: 0, option2: 'Tener la capacidad de hacer imitaciones perfectas de celebridades', option2Votes: 0 },
    { option1: 'Siempre tener que moverte al ritmo de la música que escuchas', option1Votes: 0, option2: 'Siempre tener que tararear la melodía que está en tu cabeza', option2Votes: 0 },
    { option1: 'Tener la capacidad de transformar cualquier objeto en una versión miniatura', option1Votes: 0, option2: 'Tener la capacidad de transformar cualquier objeto en una versión gigante', option2Votes: 0 },
    { option1: 'Siempre tener que saludar a las personas con un saludo inventado', option1Votes: 0, option2: 'Siempre tener que saludar a las personas con un baile improvisado', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que las cosas se iluminen al tocarlas', option1Votes: 0, option2: 'Tener la capacidad de hacer que las cosas desaparezcan al tocarlas', option2Votes: 0 },
    { option1: 'Siempre tener que hablar en rimas simples', option1Votes: 0, option2: 'Siempre tener que hablar en palabras inventadas', option2Votes: 0 },
    { option1: 'Tener la capacidad de leer las conversaciones de las plantas', option1Votes: 0, option2: 'Tener la capacidad de entender los mensajes ocultos en las nubes', option2Votes: 0 },
    { option1: 'Siempre tener que hablar con voz de bebé', option1Votes: 0, option2: 'Siempre tener que hablar con voz de anciano', option2Votes: 0 },
    { option1: 'Siempre tener que moverte como si estuvieras en un videojuego retro', option1Votes: 0, option2: 'Siempre tener que moverte como si estuvieras en un baile de TikTok', option2Votes: 0 },
    { option1: 'Tener un viaje gratis a cualquier lugar del mundo cada año', option1Votes: 0, option2: 'Tener un encuentro con tu celebridad favorita una vez en tu vida', option2Votes: 0 },
    { option1: 'Siempre tener que llevar un disfraz extravagante en público', option1Votes: 0, option2: 'Siempre tener que llevar ropa al revés en público', option2Votes: 0 },
    { option1: 'Tener la capacidad de saber el nombre de cualquier persona que veas', option1Votes: 0, option2: 'Tener la capacidad de saber el secreto más profundo de cualquier persona que veas', option2Votes: 0 },
    { option1: 'Siempre tener que reemplazar una palabra en cada frase con "cacahuete"', option1Votes: 0, option2: 'Siempre tener que reemplazar una palabra en cada frase con "piña"', option2Votes: 0 },
    { option1: 'Tener un baúl que siempre contiene exactamente lo que necesitas', option1Votes: 0, option2: 'Tener un espejo que te muestra cómo serás en 20 años', option2Votes: 0 },
    { option1: 'Siempre tener que repetir la última palabra que dices', option1Votes: 0, option2: 'Siempre tener que hacer un chasquido de dedos después de cada frase', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender el lenguaje de los pájaros', option1Votes: 0, option2: 'Tener la capacidad de entender el lenguaje de los insectos', option2Votes: 0 },
    { option1: 'Siempre tener que hablar en acertijos', option1Votes: 0, option2: 'Siempre tener que hablar en trabalenguas', option2Votes: 0 },
    { option1: 'Tener una conversación con un alienígena durante una hora', option1Votes: 0, option2: 'Tener una conversación con un fantasma durante una hora', option2Votes: 0 },
    { option1: 'Siempre tener que correr en cámara lenta', option1Votes: 0, option2: 'Siempre tener que hablar en cámara lenta', option2Votes: 0 },
    { option1: 'Tener la capacidad de transformar cualquier objeto en chocolate', option1Votes: 0, option2: 'Tener la capacidad de transformar cualquier objeto en caramelo', option2Votes: 0 },
    { option1: 'Siempre tener que usar una corona dondequiera que vayas', option1Votes: 0, option2: 'Siempre tener que usar un sombrero de vaquero dondequiera que vayas', option2Votes: 0 },
    { option1: 'Siempre tener que comer tu comida favorita en cada comida', option1Votes: 0, option2: 'Nunca más poder comer tu comida favorita', option2Votes: 0 },
    { option1: 'Tener la capacidad de tener una conversación con los animales solo una vez', option1Votes: 0, option2: 'Tener la capacidad de hablar todos los idiomas humanos por un día', option2Votes: 0 },
    { option1: 'Siempre tener que comunicarte en lenguaje de señas', option1Votes: 0, option2: 'Siempre tener que comunicarte a través de mímica', option2Votes: 0 },
    { option1: 'Tener un archivo con todos tus pensamientos pasados', option1Votes: 0, option2: 'Tener un archivo con todos tus correos electrónicos enviados del futuro', option2Votes: 0 },
    { option1: 'Siempre tener que hacer una reverencia al saludar a alguien', option1Votes: 0, option2: 'Siempre tener que hacer una pirueta al saludar a alguien', option2Votes: 0 },
    { option1: 'Siempre tener que elegir entre hablar en verso o hablar en rima', option1Votes: 0, option2: 'Siempre tener que hablar en un idioma extranjero al azar', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender los mensajes secretos de las palomas mensajeras', option1Votes: 0, option2: 'Tener la capacidad de entender los mensajes secretos de los gatos callejeros', option2Votes: 0 },
    { option1: 'Siempre tener que contar un chiste antes de hablar en serio', option1Votes: 0, option2: 'Siempre tener que contar un hecho interesante antes de hablar en serio', option2Votes: 0 },
    { option1: 'Tener una conversación con tu objeto inanimado favorito', option1Votes: 0, option2: 'Tener una conversación con tu comida favorita antes de comerla', option2Votes: 0 },
    { option1: 'Siempre tener que bailar en cualquier lugar donde escuches música', option1Votes: 0, option2: 'Siempre tener que hacer un chiste cada vez que alguien hable contigo', option2Votes: 0 },
    { option1: 'Tener un control remoto que funcione solo en personas', option1Votes: 0, option2: 'Tener un control remoto que funcione solo en objetos', option2Votes: 0 },
    { option1: 'Siempre tener que elegir entre hablar en voz baja o gritar', option1Votes: 0, option2: 'Siempre tener que hablar en un idioma desconocido', option2Votes: 0 },
    { option1: 'Tener la capacidad de encontrar siempre un estacionamiento perfecto', option1Votes: 0, option2: 'Tener la capacidad de evitar siempre las colas en cualquier lugar', option2Votes: 0 },
    { option1: 'Siempre tener que llevar un bigote falso', option1Votes: 0, option2: 'Siempre tener que llevar una nariz roja de payaso', option2Votes: 0 },
    { option1: 'Tener un sombrero que cambia de forma según tu estado de ánimo', option1Votes: 0, option2: 'Tener zapatos que te hacen saltar más alto de lo normal', option2Votes: 0 },
    { option1: 'Siempre tener que comunicarte a través de señales de humo', option1Votes: 0, option2: 'Siempre tener que comunicarte a través de señales de luz con una linterna', option2Votes: 0 },
    { option1: 'Tener la capacidad de hablar con las plantas', option1Votes: 0, option2: 'Tener la capacidad de entender el lenguaje de los objetos electrónicos', option2Votes: 0 },
    { option1: 'Siempre tener que moverte en cámara lenta cuando estás emocionado', option1Votes: 0, option2: 'Siempre tener que moverte muy rápido cuando estás nervioso', option2Votes: 0 },
    { option1: 'Tener una habitación con paredes de trampolín', option1Votes: 0, option2: 'Tener una habitación con paredes de espejos distorsionados', option2Votes: 0 },
    { option1: 'Siempre tener que hablar con voz de robot', option1Votes: 0, option2: 'Siempre tener que hablar con voz de dibujo animado', option2Votes: 0 },
    { option1: 'Tener un asistente personal invisible', option1Votes: 0, option2: 'Tener un asistente personal robot', option2Votes: 0 },
    { option1: 'Siempre tener que hacer una danza alegre cada vez que llueve', option1Votes: 0, option2: 'Siempre tener que hacer una danza triste cada vez que sale el sol', option2Votes: 0 },
    { option1: 'Tener la capacidad de traducir los ladridos de los perros', option1Votes: 0, option2: 'Tener la capacidad de traducir los maullidos de los gatos', option2Votes: 0 },
    { option1: 'Siempre tener un séquito de pingüinos siguiéndote', option1Votes: 0, option2: 'Siempre tener un séquito de flamencos siguiéndote', option2Votes: 0 },
    { option1: 'Tener un reloj que te muestra cuánto tiempo te queda de vida', option1Votes: 0, option2: 'Tener un reloj que te muestra cuántos actos de bondad has realizado', option2Votes: 0 },
    { option1: 'Siempre tener que hacer un salto mortal antes de sentarte en cualquier lugar', option1Votes: 0, option2: 'Siempre tener que hacer un giro antes de levantarte de cualquier silla', option2Votes: 0 },
    { option1: 'Tener un cojín que siempre está en la temperatura perfecta', option1Votes: 0, option2: 'Tener un cojín que emite sonidos relajantes cuando te sientas', option2Votes: 0 },
    { option1: 'Siempre tener que tener una conversación seria con una marioneta', option1Votes: 0, option2: 'Siempre tener que tener una conversación en tono cómico con un maniquí', option2Votes: 0 },
    { option1: 'Siempre tener que reemplazar una palabra en cada frase con "meow"', option1Votes: 0, option2: 'Siempre tener que reemplazar una palabra en cada frase con "quack"', option2Votes: 0 },
    { option1: 'Tener siempre un acompañante invisible que solo tú puedes ver', option1Votes: 0, option2: 'Tener siempre una sombra que tiene su propia personalidad', option2Votes: 0 },
    { option1: 'Siempre tener que hablar en rimas', option1Votes: 0, option2: 'Siempre tener que hablar en jeroglíficos', option2Votes: 0 },
    { option1: 'Siempre tener que dar un salto antes de entrar a cualquier habitación', option1Votes: 0, option2: 'Siempre tener que girar sobre ti mismo antes de sentarte en cualquier silla', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que las nubes formen figuras específicas', option1Votes: 0, option2: 'Tener la capacidad de cambiar el color del cielo a voluntad', option2Votes: 0 },
    { option1: 'Siempre tener que saludar a las personas con una reverencia', option1Votes: 0, option2: 'Siempre tener que saludar a las personas con un salto en el aire', option2Votes: 0 },
    { option1: 'Tener la capacidad de cambiar el sabor de cualquier comida a tu antojo', option1Votes: 0, option2: 'Tener la capacidad de cambiar el olor de cualquier ambiente a tu antojo', option2Votes: 0 },
    { option1: 'Siempre tener que andar a cuatro patas como un animal', option1Votes: 0, option2: 'Siempre tener que saltar en un solo pie como un canguro', option2Votes: 0 },
    { option1: 'Tener un periódico que siempre predice tu día futuro', option1Votes: 0, option2: 'Tener un espejo que siempre muestra cómo te ves en tu día futuro', option2Votes: 0 },
    { option1: 'Siempre tener que moverte como si estuvieras en un videojuego de plataformas', option1Votes: 0, option2: 'Siempre tener que moverte como si estuvieras en un videojuego de baile', option2Votes: 0 },
    { option1: 'Tener la capacidad de cambiar el color de tu piel como un camaleón', option1Votes: 0, option2: 'Tener la capacidad de cambiar el patrón de tu piel como un cebra', option2Votes: 0 },
    { option1: 'Siempre tener que hablar en verso', option1Votes: 0, option2: 'Siempre tener que hablar en onomatopeyas', option2Votes: 0 },
    { option1: 'Tener un botón que cambia el clima solo en tu ubicación', option1Votes: 0, option2: 'Tener un botón que cambia la apariencia de las personas a tu alrededor', option2Votes: 0 },
    { option1: 'Tener la capacidad de tener una conversación telepática con los animales', option1Votes: 0, option2: 'Tener la capacidad de comunicarte con las plantas a través de canciones', option2Votes: 0 },
    { option1: 'Siempre tener que contar tus pensamientos en voz alta', option1Votes: 0, option2: 'Siempre tener que hablar en un idioma inventado por ti', option2Votes: 0 },
    { option1: 'Tener la capacidad de convertir cualquier conversación en una canción', option1Votes: 0, option2: 'Tener la capacidad de convertir cualquier conversación en un poema', option2Votes: 0 },
    { option1: 'Siempre tener que hacer una pausa dramática antes de responder cualquier pregunta', option1Votes: 0, option2: 'Siempre tener que responder instantáneamente sin pensar', option2Votes: 0 },
    { option1: 'Tener un guardaespaldas gorila', option1Votes: 0, option2: 'Tener un guardaespaldas flamenco', option2Votes: 0 },
    { option1: 'Siempre tener que llevar un sombrero de sombrilla para protegerte del sol', option1Votes: 0, option2: 'Siempre tener que llevar un paraguas incluso en días despejados', option2Votes: 0 },
    { option1: 'Tener la capacidad de convertir cualquier objeto en un globo', option1Votes: 0, option2: 'Tener la capacidad de convertir cualquier objeto en una burbuja', option2Votes: 0 },
    { option1: 'Siempre tener que tomar el camino más largo para llegar a tu destino', option1Votes: 0, option2: 'Siempre tener que tomar el camino más corto pero lleno de obstáculos divertidos', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que las cosas cambien de tamaño', option1Votes: 0, option2: 'Tener la capacidad de hacer que las cosas cambien de forma', option2Votes: 0 },
    { option1: 'Siempre tener que moverte en cámara lenta durante las mañanas', option1Votes: 0, option2: 'Siempre tener que moverte a alta velocidad durante las tardes', option2Votes: 0 },
    { option1: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en comida', option1Votes: 0, option2: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en música', option2Votes: 0 },
    { option1: 'Siempre tener que comunicarte con gestos y mímica', option1Votes: 0, option2: 'Siempre tener que comunicarte a través de dibujos y garabatos', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender los suspiros de las personas', option1Votes: 0, option2: 'Tener la capacidad de entender los bostezos de las personas', option2Votes: 0 },
    { option1: 'Siempre tener que resolver acertijos antes de poder abrir una puerta', option1Votes: 0, option2: 'Siempre tener que hacer un baile antes de poder abrir una puerta', option2Votes: 0 },
    { option1: 'Tener la capacidad de cambiar la voz de las personas a tu antojo', option1Votes: 0, option2: 'Tener la capacidad de cambiar el acento de las personas a tu antojo', option2Votes: 0 },
    { option1: 'Siempre tener que llevar un tutú en eventos formales', option1Votes: 0, option2: 'Siempre tener que llevar una capa de superhéroe en eventos formales', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que las cosas leviten', option1Votes: 0, option2: 'Tener la capacidad de hacer que las cosas se vuelvan pegajosas', option2Votes: 0 },
    { option1: 'Siempre tener que contar chistes malos antes de cualquier conversación', option1Votes: 0, option2: 'Siempre tener que contar datos curiosos antes de cualquier conversación', option2Votes: 0 },
    { option1: 'Tener la capacidad de saber qué canción está sonando en la cabeza de las personas', option1Votes: 0, option2: 'Tener la capacidad de saber qué película está pasando en la mente de las personas', option2Votes: 0 },
    { option1: 'Siempre tener que moverte como si estuvieras en un video musical', option1Votes: 0, option2: 'Siempre tener que moverte como si estuvieras en una película de acción', option2Votes: 0 },
    { option1: 'Tener un teletransportador que solo funciona si haces el moonwalk', option1Votes: 0, option2: 'Tener un teletransportador que solo funciona si haces una pirueta', option2Votes: 0 },
    { option1: 'Siempre tener que llevar un tatuaje temporal con un mensaje divertido', option1Votes: 0, option2: 'Siempre tener que llevar un tatuaje temporal con un mensaje inspirador', option2Votes: 0 },
    { option1: 'Tener la capacidad de hablar con los objetos electrónicos', option1Votes: 0, option2: 'Tener la capacidad de comunicarte con las nubes a través de movimientos', option2Votes: 0 },
    { option1: 'Siempre tener que dar una pequeña actuación antes de tomar una foto', option1Votes: 0, option2: 'Siempre tener que hacer una pose extravagante antes de tomar una foto', option2Votes: 0 },
    { option1: 'Tener la capacidad de convertir tus sueños en películas animadas', option1Votes: 0, option2: 'Tener la capacidad de convertir tus pensamientos en canciones populares', option2Votes: 0 },
    { option1: 'Siempre tener que comunicarte en lenguaje de señas', option1Votes: 0, option2: 'Siempre tener que comunicarte en lenguaje morse', option2Votes: 0 },
    { option1: 'Tener un sombrero que siempre reproduce música a tu alrededor', option1Votes: 0, option2: 'Tener una bufanda que siempre te mantiene a la temperatura perfecta', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que los objetos hablen como en las películas animadas', option1Votes: 0, option2: 'Tener la capacidad de hacer que los objetos bailen como en los videos musicales', option2Votes: 0 },
    { option1: 'Siempre tener que responder preguntas solo en forma de preguntas', option1Votes: 0, option2: 'Siempre tener que responder preguntas solo en forma de refranes', option2Votes: 0 },
    { option1: 'Tener la capacidad de teletransportarte a cualquier lugar, pero solo puedes llevar contigo objetos inútiles', option1Votes: 0, option2: 'Tener la capacidad de volar, pero solo a baja velocidad y solo en círculos', option2Votes: 0 },
    { option1: 'Siempre tener que llevar una cola de sirena en lugar de piernas', option1Votes: 0, option2: 'Siempre tener que llevar orejas de conejo en lugar de orejas humanas', option2Votes: 0 },
    { option1: 'Tener la capacidad de controlar la gravedad solo en tu área cercana', option1Votes: 0, option2: 'Tener la capacidad de controlar las corrientes de aire solo en tu área cercana', option2Votes: 0 },
    { option1: 'Siempre tener que saludar a los extraños con una reverencia ninja', option1Votes: 0, option2: 'Siempre tener que saludar a los extraños con un salto al estilo de Michael Jordan', option2Votes: 0 },
    { option1: 'Tener un retrato tuyo que envejece en lugar de tú', option1Votes: 0, option2: 'Tener un espejo que refleja tu versión más feliz', option2Votes: 0 },
    { option1: 'Siempre tener que bailar cada vez que escuchas música, sin importar el lugar', option1Votes: 0, option2: 'Siempre tener que cantar cada vez que escuchas música, sin importar el lugar', option2Votes: 0 },
    { option1: 'Siempre tener que comunicarte en rimas', option1Votes: 0, option2: 'Siempre tener que comunicarte en poesía épica', option2Votes: 0 },
    { option1: 'Tener un control remoto que solo funciona en personas', option1Votes: 0, option2: 'Tener un control remoto que solo funciona en animales', option2Votes: 0 },
    { option1: 'Siempre tener que dar un abrazo a cualquier persona que te hable', option1Votes: 0, option2: 'Siempre tener que dar un apretón de manos a cualquier persona que te hable', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender todos los lenguajes de programación', option1Votes: 0, option2: 'Tener la capacidad de entender todos los lenguajes humanos', option2Votes: 0 },
    { option1: 'Siempre tener que usar un disfraz extravagante para cualquier ocasión', option1Votes: 0, option2: 'Siempre tener que usar un disfraz que coincida con el tema de la ocasión', option2Votes: 0 },
    { option1: 'Tener la capacidad de convertir cualquier cosa en confeti', option1Votes: 0, option2: 'Tener la capacidad de convertir cualquier cosa en pompas de jabón', option2Votes: 0 },
    { option1: 'Siempre tener que hacer un baile antes de entrar a cualquier habitación', option1Votes: 0, option2: 'Siempre tener que hacer una pirueta antes de entrar a cualquier habitación', option2Votes: 0 },
    { option1: 'Tener un botón que haga que las cosas cambien de color', option1Votes: 0, option2: 'Tener un botón que haga que las cosas cambien de sabor', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender las conversaciones de los insectos', option1Votes: 0, option2: 'Tener la capacidad de entender las conversaciones de las aves', option2Votes: 0 },
    { option1: 'Siempre tener que usar gafas de sol, incluso en interiores', option1Votes: 0, option2: 'Siempre tener que llevar un paraguas, incluso en días soleados', option2Votes: 0 },
    { option1: 'Tener la capacidad de transformar cualquier objeto en un instrumento musical', option1Votes: 0, option2: 'Tener la capacidad de transformar cualquier objeto en una obra de arte', option2Votes: 0 },
    { option1: 'Tener la capacidad de convertir cualquier objeto en una planta', option1Votes: 0, option2: 'Tener la capacidad de convertir cualquier objeto en una mascota', option2Votes: 0 },
    { option1: 'Siempre tener que hablar en voz alta lo que piensas', option1Votes: 0, option2: 'Siempre tener que comunicarte a través de mensajes escritos', option2Votes: 0 },
    { option1: 'Tener la capacidad de teletransportarte a cualquier lugar del mundo', option1Votes: 0, option2: 'Tener la capacidad de volar a la velocidad de una bicicleta', option2Votes: 0 },
    { option1: 'Siempre tener que saludar a las personas con un saludo de una cultura diferente', option1Votes: 0, option2: 'Siempre tener que saludar a las personas con un abrazo', option2Votes: 0 },
    { option1: 'Tener la capacidad de cambiar el color de tus ojos según tu estado de ánimo', option1Votes: 0, option2: 'Tener la capacidad de cambiar la forma de tus orejas según tu estado de ánimo', option2Votes: 0 },
    { option1: 'Siempre tener que hablar con un acento extranjero', option1Votes: 0, option2: 'Siempre tener que hablar como un personaje de película', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que los objetos cobren vida por un día', option1Votes: 0, option2: 'Tener la capacidad de hacer que los objetos se conviertan en comida', option2Votes: 0 },
    { option1: 'Siempre tener que tener una conversación en voz alta contigo mismo', option1Votes: 0, option2: 'Siempre tener que tener una conversación susurrante contigo mismo', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que las sombras cobren vida', option1Votes: 0, option2: 'Tener la capacidad de hacer que los reflejos hablen', option2Votes: 0 },
    { option1: 'Siempre tener que saludar a los extraños con un chiste', option1Votes: 0, option2: 'Siempre tener que saludar a los extraños con un cumplido', option2Votes: 0 },
    { option1: 'Tener la capacidad de transformar cualquier conversación en una canción', option1Votes: 0, option2: 'Tener la capacidad de transformar cualquier conversación en una historia de terror', option2Votes: 0 },
    { option1: 'Siempre tener que llevar una pizarra y tiza para escribir mensajes', option1Votes: 0, option2: 'Siempre tener que llevar una pizarra y imanes para escribir mensajes', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender y hablar con los emojis', option1Votes: 0, option2: 'Tener la capacidad de entender y hablar con los símbolos matemáticos', option2Votes: 0 },
    { option1: 'Siempre tener que hacer beatbox cada vez que te saludan', option1Votes: 0, option2: 'Siempre tener que tararear una canción cada vez que te saludan', option2Votes: 0 },
    { option1: 'Tener una colección de ropa de disfraces de tamaño mini para tus mascotas', option1Votes: 0, option2: 'Tener una colección de sombreros elegantes de tamaño gigante para ti', option2Votes: 0 },
    { option1: 'Tener la capacidad de transformar cualquier situación en una escena de comedia', option1Votes: 0, option2: 'Tener la capacidad de transformar cualquier situación en una escena de película de terror', option2Votes: 0 },
    { option1: 'Siempre tener que hacer beatbox mientras bailas', option1Votes: 0, option2: 'Siempre tener que hacer palmas al ritmo mientras caminas', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que los objetos desaparezcan temporalmente', option1Votes: 0, option2: 'Tener la capacidad de hacer que los objetos se multipliquen temporalmente', option2Votes: 0 },
    { option1: 'Tener una nube personal que te sigue y te proporciona sombra', option1Votes: 0, option2: 'Tener un séquito de mariposas que te siguen a todas partes', option2Votes: 0 },
    { option1: 'Siempre tener que llevar un globo atado a tu muñeca', option1Votes: 0, option2: 'Siempre tener que llevar una campana que suene al caminar', option2Votes: 0 },
    { option1: 'Tener un asiento en la primera fila de cualquier espectáculo', option1Votes: 0, option2: 'Tener la mejor vista desde la última fila de cualquier espectáculo', option2Votes: 0 },
    { option1: 'Siempre tener que viajar en el tiempo solo hacia el pasado', option1Votes: 0, option2: 'Siempre tener que viajar en el tiempo solo hacia el futuro', option2Votes: 0 },
    { option1: 'Tener la capacidad de entender el lenguaje de los animales marinos', option1Votes: 0, option2: 'Tener la capacidad de entender el lenguaje de los pájaros', option2Votes: 0 },
    { option1: 'Siempre tener que comunicarte en rima', option1Votes: 0, option2: 'Siempre tener que comunicarte en poesía épica', option2Votes: 0 },
    { option1: 'Tener un robot que haga todas tus tareas domésticas', option1Votes: 0, option2: 'Tener un dron que te entregue pizza en cualquier lugar', option2Votes: 0 },
    { option1: 'Siempre tener que bailar en público cada vez que escuchas música', option1Votes: 0, option2: 'Siempre tener que cantar en público cada vez que alguien toca un instrumento', option2Votes: 0 },
    { option1: 'Tener la capacidad de comunicarte con los personajes de los libros', option1Votes: 0, option2: 'Tener la capacidad de viajar a los mundos de los libros', option2Votes: 0 },
    { option1: 'Siempre tener una banda sonora personal que suene en tu cabeza', option1Votes: 0, option2: 'Siempre tener un narrador que describa tus acciones en voz alta', option2Votes: 0 },
    { option1: 'Tener una máquina que convierta cualquier alimento en tu comida favorita', option1Votes: 0, option2: 'Tener una máquina que convierta cualquier objeto en una obra de arte', option2Votes: 0 },
    { option1: 'Siempre poder escuchar lo que la naturaleza está diciendo', option1Votes: 0, option2: 'Siempre poder entender las conversaciones de los objetos cotidianos', option2Votes: 0 },
    { option1: 'Tener un vaso que siempre se llena de tu bebida favorita', option1Votes: 0, option2: 'Tener una nevera que siempre esté llena de tu comida favorita', option2Votes: 0 },
    { option1: 'Siempre ser el ganador en cualquier juego que juegues', option1Votes: 0, option2: 'Siempre ser el mejor en cualquier deporte que practiques', option2Votes: 0 },
    { option1: 'Tener la capacidad de hablar con los fantasmas', option1Votes: 0, option2: 'Tener la capacidad de predecir el futuro solo en sueños', option2Votes: 0 },
    { option1: 'Siempre tener un sombrero que hable en tu cabeza', option1Votes: 0, option2: 'Siempre tener un par de zapatos que te den consejos', option2Votes: 0 },
    { option1: 'Tener un robot que te siga y haga cumplidos constantemente', option1Votes: 0, option2: 'Tener un dron que te siga y tome fotos de tus mejores momentos', option2Votes: 0 },
    { option1: 'Siempre tener un asiento especial reservado para ti en el transporte público', option1Votes: 0, option2: 'Siempre tener la capacidad de viajar gratis a cualquier lugar', option2Votes: 0 },
    { option1: 'Siempre tener una maleta que contiene lo que necesitas en el momento justo', option1Votes: 0, option2: 'Siempre tener un abanico que te protege de cualquier clima', option2Votes: 0 },
    { option1: 'Tener un espejo que siempre te muestra como un superhéroe', option1Votes: 0, option2: 'Tener un espejo que siempre te muestra como un villano carismático', option2Votes: 0 },
    { option1: 'Siempre tener la capacidad de encontrar tesoros escondidos', option1Votes: 0, option2: 'Siempre tener la capacidad de encontrar atajos secretos', option2Votes: 0 },
    { option1: 'Tener la capacidad de traducir cualquier idioma antiguo', option1Votes: 0, option2: 'Tener la capacidad de hablar el idioma de los extraterrestres', option2Votes: 0 },
    { option1: 'Siempre tener una máquina que convierte tus sueños en deliciosos postres', option1Votes: 0, option2: 'Siempre tener una máquina que convierte tus pesadillas en emocionantes aventuras', option2Votes: 0 },
    { option1: 'Tener un séquito de mariachis que te sigue y toca música en tus momentos especiales', option1Votes: 0, option2: 'Tener un coro de ángeles que aparece siempre que necesitas inspiración', option2Votes: 0 },
    { option1: 'Siempre tener la habilidad de encontrar dinero en los bolsillos de cualquier prenda que toques', option1Votes: 0, option2: 'Siempre tener la habilidad de encontrar lo que estás buscando, incluso si está perdido', option2Votes: 0 },
    { option1: 'Tener un botón que haga que todo el mundo empiece a bailar cuando lo presionas', option1Votes: 0, option2: 'Tener un botón que silencie todo el ruido a tu alrededor cuando lo presionas', option2Votes: 0 },
    { option1: 'Siempre hacer que los semáforos se pongan en verde cuando te acercas', option1Votes: 0, option2: 'Siempre hacer que el viento sople en la dirección que deseas', option2Votes: 0 },
    { option1: 'Tener una colección de sombreros que te otorgan superpoderes diferentes', option1Votes: 0, option2: 'Tener una colección de zapatos que te permiten caminar en cualquier superficie', option2Votes: 0 },
    { option1: 'Siempre poder convocar una lluvia de confeti en cualquier celebración', option1Votes: 0, option2: 'Siempre poder hacer que aparezcan fuegos artificiales en el cielo en cualquier momento', option2Votes: 0 },
    { option1: 'Tener un espejo que te muestre cómo te verías en diferentes épocas de la historia', option1Votes: 0, option2: 'Tener un espejo que te muestre cómo te verías en un universo paralelo', option2Votes: 0 },
    { option1: 'Siempre saber exactamente qué regalo hará feliz a cualquier persona', option1Votes: 0, option2: 'Siempre saber cuál será el próximo meme viral antes de que se vuelva famoso', option2Votes: 0 },
    { option1: 'Tener un reloj que te permita ralentizar o acelerar el tiempo a tu voluntad', option1Votes: 0, option2: 'Tener una puerta que te lleve a lugares exóticos de todo el mundo', option2Votes: 0 },
    { option1: 'Siempre tener una lista de reproducción musical perfecta para cada momento de tu vida', option1Votes: 0, option2: 'Siempre tener una lista de reproducción que haga que todos bailen sin importar la ocasión', option2Votes: 0 },
    { option1: 'Tener la habilidad de hacer que cualquier comida sea deliciosa con solo tocarla', option1Votes: 0, option2: 'Tener la habilidad de transformar objetos cotidianos en deliciosos postres', option2Votes: 0 },
    { option1: 'Siempre saber cuándo alguien te está mintiendo', option1Votes: 0, option2: 'Siempre saber cuándo alguien está pensando en un piropo para ti', option2Votes: 0 },
    { option1: 'Tener un par de lentes que te muestren el mundo como una obra de arte', option1Votes: 0, option2: 'Tener un par de lentes que te permitan ver eventos futuros en forma de pequeños avances', option2Votes: 0 },
    { option1: 'Siempre tener una caja de Pandora que solo contiene sorpresas agradables', option1Votes: 0, option2: 'Siempre tener una bolsa que te otorga lo que necesitas en el momento justo', option2Votes: 0 },
    { option1: 'Tener un carro que nunca necesita combustible y se convierte en cualquier vehículo', option1Votes: 0, option2: 'Tener una bicicleta que te lleva a lugares mágicos y lejanos', option2Votes: 0 },
    { option1: 'Siempre tener una capa que te permita volar cuando la necesitas', option1Votes: 0, option2: 'Siempre tener un paraguas que te proteja de cualquier desastre natural', option2Votes: 0 },
    { option1: 'Tener la habilidad de hacer que todos a tu alrededor se sientan felices', option1Votes: 0, option2: 'Tener la habilidad de calmar a todos en situaciones estresantes', option2Votes: 0 },
    { option1: 'Siempre tener la capacidad de convocar a tu banda de música favorita para tocar en tu cumpleaños', option1Votes: 0, option2: 'Siempre tener la capacidad de invitar a tus actores o actrices favoritos a tu cena familiar', option2Votes: 0 },
    { option1: 'Tener un libro que te cuente historias personalizadas de tu vida', option1Votes: 0, option2: 'Tener una varita mágica que resuelva cualquier problema cotidiano', option2Votes: 0 },
    { option1: 'Siempre tener un perro que hable con un sentido del humor excepcional', option1Votes: 0, option2: 'Siempre tener un gato que te hable con sabios consejos de vida', option2Votes: 0 },
    { option1: 'Tener la habilidad de tocar cualquier instrumento musical sin práctica', option1Votes: 0, option2: 'Tener la habilidad de pintar obras de arte sin tener experiencia previa', option2Votes: 0 },
    { option1: 'Siempre ser capaz de recordar nombres y caras de todas las personas que conoces', option1Votes: 0, option2: 'Siempre ser capaz de hacer reír a cualquiera sin importar la situación', option2Votes: 0 },
    { option1: 'Tener un tatuaje que cambia de diseño según tu estado de ánimo', option1Votes: 0, option2: 'Tener un collar que brilla en la oscuridad y te guía en la noche', option2Votes: 0 },
    { option1: 'Siempre tener la capacidad de convocar un desfile de moda personalizado', option1Votes: 0, option2: 'Siempre tener la capacidad de organizar una fiesta sorpresa increíble para tus amigos', option2Votes: 0 },
    { option1: 'Tener una puerta que te lleve a una biblioteca infinita llena de conocimiento', option1Votes: 0, option2: 'Tener un reloj que te permita viajar en el tiempo a eventos históricos', option2Votes: 0 },
    { option1: 'Siempre saber cómo resolver rompecabezas complicados de inmediato', option1Votes: 0, option2: 'Siempre saber la respuesta correcta a cualquier pregunta en una prueba', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que los objetos cambien de color según tu estado de ánimo', option1Votes: 0, option2: 'Tener la capacidad de hacer que los objetos generen fragancias deliciosas', option2Votes: 0 },
    { option1: 'Siempre poder identificar los lugares más hermosos para ver la puesta de sol', option1Votes: 0, option2: 'Siempre poder planear las noches más emocionantes en cualquier ciudad', option2Votes: 0 },
    { option1: 'Tener un sombrero que siempre encuentra el camino de regreso a casa', option1Votes: 0, option2: 'Tener un par de zapatos que te llevan a cualquier lugar que imagines', option2Votes: 0 },
    { option1: 'Siempre poder organizar una fiesta sorpresa perfecta para tus amigos', option1Votes: 0, option2: 'Siempre poder organizar una noche de juegos épica para tus amigos', option2Votes: 0 },
    { option1: 'Tener un espejo que te muestra cómo serías si fueras una caricatura', option1Votes: 0, option2: 'Tener un espejo que te muestra cómo serías si fueras un personaje de cuento de hadas', option2Votes: 0 },
    { option1: 'Siempre saber cuál es el deseo de alguien antes de que lo pidan', option1Votes: 0, option2: 'Siempre poder adivinar cuál será la próxima gran tendencia de moda', option2Votes: 0 },
    { option1: 'Tener la capacidad de convertir cualquier objeto en una deliciosa barra de chocolate', option1Votes: 0, option2: 'Tener la capacidad de convertir cualquier objeto en una canción pegajosa', option2Votes: 0 },
    { option1: 'Siempre poder encontrar dinero en monederos y bolsillos olvidados', option1Votes: 0, option2: 'Siempre poder encontrar tesoros escondidos en tu jardín', option2Votes: 0 },
    { option1: 'Tener un asistente personal que organiza fiestas sorpresa en tu honor', option1Votes: 0, option2: 'Tener un asistente personal que planifica viajes espontáneos a lugares emocionantes', option2Votes: 0 },
    { option1: 'Siempre poder hacer que los objetos se iluminen en la oscuridad', option1Votes: 0, option2: 'Siempre poder hacer que los objetos se vuelvan invisibles temporalmente', option2Votes: 0 },
    { option1: 'Tener una mochila que siempre contiene tus bocadillos favoritos', option1Votes: 0, option2: 'Tener una mochila que te permite explorar cualquier libro que desees', option2Votes: 0 },
    { option1: 'Siempre saber cuál es el regalo perfecto para cualquier ocasión', option1Votes: 0, option2: 'Siempre poder envolver regalos de manera creativa y sorprendente', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que los objetos hablen y cuenten historias', option1Votes: 0, option2: 'Tener la capacidad de hacer que las sombras cobren vida y realicen obras de teatro', option2Votes: 0 },
    { option1: 'Siempre poder convocar una tormenta de confeti en los momentos más emocionantes', option1Votes: 0, option2: 'Siempre poder crear fuegos artificiales con solo chasquear los dedos', option2Votes: 0 },
    { option1: 'Tener un cajero automático que te da el doble de dinero cada vez', option1Votes: 0, option2: 'Tener una máquina expendedora que te da el refrigerio perfecto según tu estado de ánimo', option2Votes: 0 },
    { option1: 'Siempre tener la capacidad de convertir la lluvia en una colorida lluvia de confeti', option1Votes: 0, option2: 'Siempre tener la capacidad de convertir la nieve en una alfombra mágica', option2Votes: 0 },
    { option1: 'Tener una puerta mágica que te lleve a cualquier lugar del mundo', option1Votes: 0, option2: 'Tener una ventana mágica que te permita ver eventos en el pasado o el futuro', option2Votes: 0 },
    { option1: 'Siempre saber cuándo alguien está mintiendo con solo mirar a sus ojos', option1Votes: 0, option2: 'Siempre poder detectar la próxima gran tendencia de moda antes que nadie', option2Votes: 0 },
    { option1: 'Tener una taza que siempre llena con tu bebida favorita', option1Votes: 0, option2: 'Tener una taza que transforma cualquier bebida en la que sueñas', option2Votes: 0 },
    { option1: 'Siempre poder hacer que los objetos se muevan al ritmo de la música', option1Votes: 0, option2: 'Siempre poder hacer que los objetos se conviertan en obras de arte en movimiento', option2Votes: 0 },
    { option1: 'Siempre poder adivinar cuál será el próximo meme viral', option1Votes: 0, option2: 'Siempre poder crear memes que se vuelvan virales en segundos', option2Votes: 0 },
    { option1: 'Tener la habilidad de hacer que las canciones pegajosas de otras personas se conviertan en éxitos', option1Votes: 0, option2: 'Tener la habilidad de componer canciones que hagan bailar a todo el mundo', option2Votes: 0 },
    { option1: 'Tener una puerta secreta en tu casa que te lleve a tu lugar de ensueño', option1Votes: 0, option2: 'Tener un espejo mágico que te muestre otros mundos', option2Votes: 0 },
    { option1: 'Siempre poder encontrar el regalo perfecto para cualquier ocasión', option1Votes: 0, option2: 'Siempre poder envolver regalos de manera sorprendente y creativa', option2Votes: 0 },
    { option1: 'Tener un bolso que siempre contiene exactamente lo que necesitas', option1Votes: 0, option2: 'Tener un par de zapatos que te llevan a cualquier lugar que desees', option2Votes: 0 },
    { option1: 'Siempre poder organizar fiestas sorpresa épicas para tus amigos', option1Votes: 0, option2: 'Siempre poder organizar noches de juegos inolvidables para tus amigos', option2Votes: 0 },
    { option1: 'Tener una máquina que transforma objetos aburridos en divertidos juguetes', option1Votes: 0, option2: 'Tener una máquina que convierte tareas aburridas en emocionantes aventuras', option2Votes: 0 },
    { option1: 'Siempre saber cuándo alguien necesita un abrazo reconfortante', option1Votes: 0, option2: 'Siempre saber cómo hacer que alguien se sienta especial y apreciado', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que las plantas florezcan con solo tocarlas', option1Votes: 0, option2: 'Tener la capacidad de hacer que los objetos cotidianos cobren vida y cuenten chistes', option2Votes: 0 },
    { option1: 'Siempre poder convertir la lluvia en una colorida lluvia de confeti', option1Votes: 0, option2: 'Siempre poder convertir la nieve en una suave almohada para saltar', option2Votes: 0 },
    { option1: 'Tener una linterna que ilumina el camino y proyecta constelaciones en el cielo', option1Votes: 0, option2: 'Tener un reloj de arena que te permite viajar atrás en el tiempo un minuto al darle la vuelta', option2Votes: 0 },
    { option1: 'Siempre poder adivinar el próximo meme viral antes de que se vuelva famoso', option1Votes: 0, option2: 'Siempre poder crear memes que hagan reír a todo el mundo', option2Votes: 0 },
    { option1: 'Tener una caja de música que toca la canción que necesitas escuchar en ese momento', option1Votes: 0, option2: 'Tener un álbum de fotos que muestra tus recuerdos más felices en forma de películas', option2Votes: 0 },
    { option1: 'Siempre poder hacer que los objetos se iluminen en la oscuridad al ritmo de tu música favorita', option1Votes: 0, option2: 'Siempre poder convertir las sombras en obras de arte en movimiento', option2Votes: 0 },
    { option1: 'Tener un asistente personal que encuentra los eventos más emocionantes que ocurren en tu ciudad', option1Votes: 0, option2: 'Tener un asistente personal que crea tus propias aventuras y te lleva a lugares inexplorados', option2Votes: 0 },
    { option1: 'Siempre poder adivinar cuál será el próximo destino de tus vacaciones soñadas', option1Votes: 0, option2: 'Siempre poder organizar un viaje espontáneo y emocionante en cualquier momento', option2Votes: 0 },
    { option1: 'Tener una puerta mágica que te lleve a la playa más hermosa que puedas imaginar', option1Votes: 0, option2: 'Tener una ventana mágica que te permita ver lugares exóticos de todo el mundo', option2Votes: 0 },
    { option1: 'Siempre saber cuál es la película perfecta para animar a alguien', option1Votes: 0, option2: 'Siempre poder adivinar el género de música que hará que alguien baile de inmediato', option2Votes: 0 },
    { option1: 'Tener una mochila que siempre contiene tus bocadillos favoritos sin importar dónde estés', option1Votes: 0, option2: 'Tener una mochila que te permite explorar los libros de tu biblioteca personal en cualquier momento', option2Votes: 0 },
    { option1: 'Siempre poder hacer que los objetos aburridos se conviertan en divertidos juegos de mesa', option1Votes: 0, option2: 'Siempre poder hacer que las tareas monótonas se conviertan en emocionantes misiones', option2Votes: 0 },
    { option1: 'Tener un perro que siempre encuentra tesoros escondidos en tu jardín', option1Votes: 0, option2: 'Tener un gato que siempre detecta la próxima tendencia de moda antes que nadie', option2Votes: 0 },
    { option1: 'Siempre poder hacer que las canciones pegajosas de otras personas se conviertan en éxitos en segundos', option1Votes: 0, option2: 'Siempre poder componer canciones que hagan que la gente cante y baile de inmediato', option2Votes: 0 },
    { option1: 'Siempre poder organizar un picnic perfecto con solo un chasquido de dedos', option1Votes: 0, option2: 'Siempre poder organizar un día de juegos en el parque lleno de risas y diversión', option2Votes: 0 },
    { option1: 'Tener un reloj que detiene el tiempo durante cinco minutos cada vez que lo miras', option1Votes: 0, option2: 'Tener un reloj de arena que te permite viajar atrás en el tiempo para revivir momentos especiales', option2Votes: 0 },
    { option1: 'Siempre saber cuándo alguien necesita un consejo amable y sabio', option1Votes: 0, option2: 'Siempre saber cómo hacer que alguien se sienta empoderado y capaz de enfrentar desafíos', option2Votes: 0 },
    { option1: 'Tener la capacidad de hacer que las plantas hablen y compartan secretos sobre el mundo natural', option1Votes: 0, option2: 'Tener la capacidad de hacer que los objetos inanimados formen un coro y canten canciones alegres', option2Votes: 0 },
    { option1: 'Siempre poder transformar los días grises en días llenos de colores brillantes', option1Votes: 0, option2: 'Siempre poder hacer que los momentos aburridos se conviertan en momentos de emoción y aventura', option2Votes: 0 },
    { option1: 'Tener un dispositivo que traduce los ladridos de perros en mensajes divertidos', option1Votes: 0, option2: 'Tener un dispositivo que traduce los maullidos de gatos en poesía elegante', option2Votes: 0 },
    { option1: 'Siempre poder convertir cualquier actividad cotidiana en un espectáculo de circo', option1Votes: 0, option2: 'Siempre poder convertir cualquier tarea doméstica en un número de baile emocionante', option2Votes: 0 },
    { option1: 'Tener una nevera que siempre está llena de tus comidas favoritas', option1Votes: 0, option2: 'Tener una despensa que siempre se reabastece con los ingredientes necesarios para tu próxima receta', option2Votes: 0 },
    { option1: 'Siempre poder adivinar qué canción se convertirá en un éxito antes de que sea lanzada', option1Votes: 0, option2: 'Siempre poder tocar la guitarra de aire y que suene como la canción que desees', option2Votes: 0 },
    { option1: 'Tener una pluma que crea dibujos animados en el aire mientras escribes', option1Votes: 0, option2: 'Tener un pincel que pinta paisajes asombrosos en la superficie del agua', option2Votes: 0 },
    { option1: 'Siempre saber cómo hacer que una conversación aburrida se convierta en una comedia improvisada', option1Votes: 0, option2: 'Siempre saber cómo convertir una situación incómoda en un espectáculo de stand-up', option2Votes: 0 },
    { option1: 'Tener un par de zapatos que te permiten caminar por las nubes', option1Votes: 0, option2: 'Tener una bufanda que te transporta a los lugares más hermosos del mundo', option2Votes: 0 },
    { option1: 'Siempre poder encontrar el libro perfecto para cada persona en cualquier biblioteca', option1Votes: 0, option2: 'Siempre poder escribir el libro perfecto que hace que la gente se enamore de la lectura', option2Votes: 0 },
    { option1: 'Tener un control remoto que te permite pausar y retroceder momentos de tu vida', option1Votes: 0, option2: 'Tener unas gafas que te muestran los momentos más felices de tu futuro', option2Votes: 0 },
    { option1: 'Siempre poder adivinar la solución de cualquier acertijo o enigma', option1Votes: 0, option2: 'Siempre poder crear acertijos desafiantes que hagan que las mentes brillen', option2Votes: 0 },
    { option1: 'Tener una lámpara que te permite iluminar la noche con luces de colores', option1Votes: 0, option2: 'Tener una fuente que vierte chocolate en cualquier momento que lo desees', option2Votes: 0 },
    { option1: 'Siempre poder encontrar una pista de baile en medio de cualquier lugar', option1Votes: 0, option2: 'Siempre poder hacer que la música suene en cualquier lugar y convertirlo en una fiesta', option2Votes: 0 },
    { option1: 'Tener una máquina que convierte tus pensamientos en dulces deliciosos', option1Votes: 0, option2: 'Tener una máquina que convierte tus sueños en aventuras virtuales', option2Votes: 0 },
    { option1: 'Siempre saber cuál es el chiste perfecto para romper el hielo en cualquier situación', option1Votes: 0, option2: 'Siempre saber cuál es la historia más fascinante para mantener a todos entretenidos', option2Votes: 0 },
    { option1: 'Tener un sombrero que te permite volar como un pájaro', option1Votes: 0, option2: 'Tener un par de guantes que te permiten deslizarte como un delfín en el agua', option2Votes: 0 },
    { option1: 'Siempre poder encontrar un refugio acogedor en medio de una tormenta', option1Votes: 0, option2: 'Siempre poder encender un faro que guía a los perdidos de regreso a casa', option2Votes: 0 },
    { option1: 'Tener una caja de herramientas que se convierte en instrumentos musicales', option1Votes: 0, option2: 'Tener una caja de arte que transforma tus ideas en obras maestras visuales', option2Votes: 0 },
    { option1: 'Siempre poder encontrar el juego de mesa perfecto para cualquier grupo', option1Votes: 0, option2: 'Siempre poder transformar cualquier lugar en un parque de diversiones de la infancia', option2Votes: 0 },
    { option1: 'Tener un cojín que te da sueños mágicos y aventuras nocturnas', option1Votes: 0, option2: 'Tener un espejo que te muestra tu versión más segura y valiente', option2Votes: 0 },
    { option1: 'Siempre poder hacer que los abrazos sean como recargas de energía positiva', option1Votes: 0, option2: 'Siempre poder hacer que las sonrisas sean contagiosas y hagan que todos se sientan felices', option2Votes: 0 },
    { option1: 'Tener una escalera que te lleva a cualquier lugar que desees explorar', option1Votes: 0, option2: 'Tener una brújula que te guía hacia experiencias emocionantes', option2Votes: 0 },
    { option1: 'Siempre saber cómo crear una tradición especial que reúna a todos tus seres queridos', option1Votes: 0, option2: 'Siempre saber cómo hacer que cualquier día se sienta como una celebración inolvidable', option2Votes: 0 },
    { option1: 'Tener un par de lentes que te permiten ver el mundo en cámara lenta', option1Votes: 0, option2: 'Tener una diadema que te muestra el mundo en cámara rápida para disfrutar de la diversión', option2Votes: 0 },
    { option1: 'Siempre poder convertir una caminata en una emocionante expedición', option1Votes: 0, option2: 'Siempre poder hacer que cualquier viaje en automóvil sea un emocionante rally', option2Votes: 0 },
    { option1: 'Tener una radio que solo sintoniza estaciones de música que te hacen feliz', option1Votes: 0, option2: 'Tener un reproductor de música que selecciona canciones basadas en tu estado de ánimo actual', option2Votes: 0 },
    { option1: 'Siempre poder encontrar la historia perfecta para dormir que te lleva a dulces sueños', option1Votes: 0, option2: 'Siempre poder crear historias mágicas para los demás que los hacen dormir con una sonrisa', option2Votes: 0 },
    { option1: 'Tener una máquina que convierte los problemas en soluciones creativas', option1Votes: 0, option2: 'Tener una máquina que convierte los obstáculos en desafíos emocionantes', option2Votes: 0 },
    { option1: 'Siempre saber cómo convertir un día lluvioso en una aventura acuática emocionante', option1Votes: 0, option2: 'Siempre saber cómo transformar un día soleado en una búsqueda del tesoro sorpresa', option2Votes: 0 },
    { option1: 'Tener un reloj que te permite viajar atrás en el tiempo por un día', option1Votes: 0, option2: 'Tener un reloj que te permite saltar hacia el futuro por un día', option2Votes: 0 },
    { option1: 'Siempre poder encontrar tesoros escondidos en tiendas de segunda mano', option1Votes: 0, option2: 'Siempre poder encontrar gangas increíbles en cualquier tienda', option2Votes: 0 },
    { option1: 'Tener una brújula que te lleva a los lugares más exóticos del mundo', option1Votes: 0, option2: 'Tener un mapa que te muestra los lugares más misteriosos de la Tierra', option2Votes: 0 },
    { option1: 'Siempre poder convocar un desfile espontáneo en cualquier momento', option1Votes: 0, option2: 'Siempre poder organizar una fiesta sorpresa en segundos', option2Votes: 0 },
    { option1: 'Tener una linterna que revela tesoros ocultos en la oscuridad', option1Votes: 0, option2: 'Tener un candelabro que ilumina cualquier habitación con un ambiente mágico', option2Votes: 0 },
    { option1: 'Siempre poder encontrar el atuendo perfecto para cualquier ocasión', option1Votes: 0, option2: 'Siempre poder aconsejar a los demás sobre la moda más elegante', option2Votes: 0 },
    { option1: 'Tener un espejo que te muestra cómo te verías con cualquier peinado', option1Votes: 0, option2: 'Tener una peluca que cambia de estilo automáticamente según tu estado de ánimo', option2Votes: 0 },
    { option1: 'Siempre saber cómo hacer que cualquier tarea aburrida sea un desafío emocionante', option1Votes: 0, option2: 'Siempre saber cómo convertir una tarea tediosa en una competencia divertida', option2Votes: 0 },
    { option1: 'Tener una sartén que cocina cualquier comida en segundos', option1Votes: 0, option2: 'Tener un horno que hornea los pasteles más deliciosos en tiempo récord', option2Votes: 0 },
    { option1: 'Siempre poder encender fuegos artificiales en cualquier celebración', option1Votes: 0, option2: 'Siempre poder hacer que los cielos se llenen de luces deslumbrantes en tu honor', option2Votes: 0 },
    { option1: 'Tener un par de anteojos que traducen cualquier idioma instantáneamente', option1Votes: 0, option2: 'Tener un sombrero que te permite comprender los idiomas de los animales', option2Votes: 0 },
    { option1: 'Tener una pluma que escribe canciones inolvidables con solo tocarla', option1Votes: 0, option2: 'Tener una flauta que crea melodías mágicas al soplar suavemente', option2Votes: 0 },
    { option1: 'Siempre saber cómo hacer que cualquier día lluvioso se convierta en una aventura épica', option1Votes: 0, option2: 'Siempre saber cómo convertir un día soleado en una búsqueda de tesoros inolvidable', option2Votes: 0 },
    { option1: 'Tener una llave que abre puertas hacia dimensiones paralelas', option1Votes: 0, option2: 'Tener una vara mágica que transforma lugares cotidianos en paisajes épicos', option2Votes: 0 },
    { option1: 'Siempre poder convertir una caminata en un safari de descubrimiento de animales', option1Votes: 0, option2: 'Siempre poder convertir un paseo por el bosque en una búsqueda de criaturas mágicas', option2Votes: 0 },
    { option1: 'Tener un sombrero que te permite hablar con los pájaros', option1Votes: 0, option2: 'Tener un anillo que te permite entender el lenguaje de los ríos y arroyos', option2Votes: 0 },
    { option1: 'Siempre saber cómo hacer que cualquier día de compras sea una cacería de tesoros', option1Votes: 0, option2: 'Siempre saber cómo hacer que cualquier compra en línea sea una experiencia emocionante', option2Votes: 0 },
    { option1: 'Tener un bolígrafo que traduce tus pensamientos en poesía', option1Votes: 0, option2: 'Tener un lápiz que crea obras de arte a partir de tus pensamientos', option2Votes: 0 },
    { option1: 'Siempre poder encontrar un par de zapatos mágicos que te llevan a donde quieras', option1Votes: 0, option2: 'Siempre poder encontrar un sombrero que te permite volar a lugares lejanos', option2Votes: 0 },
    { option1: 'Tener una caja de música que crea canciones basadas en tus emociones', option1Votes: 0, option2: 'Tener un tambor que toca ritmos según tu estado de ánimo', option2Votes: 0 },
    { option1: 'Siempre poder hacer que cualquier película se convierta en una experiencia interactiva', option1Votes: 0, option2: 'Siempre poder hacer que cualquier serie de televisión tenga finales alternativos', option2Votes: 0 },
    { option1: 'Tener un par de gafas que te permiten ver el mundo como un cuadro de arte', option1Votes: 0, option2: 'Tener una máquina de tatuajes que aplica diseños temporales basados en tus emociones', option2Votes: 0 },
    { option1: 'Siempre saber cómo organizar una búsqueda del tesoro que emocione a todos', option1Votes: 0, option2: 'Siempre saber cómo organizar un juego de rol que sumerja a todos en un mundo mágico', option2Votes: 0 },
    { option1: 'Tener una pizarra mágica que muestra respuestas a cualquier pregunta', option1Votes: 0, option2: 'Tener una caja de adivinanzas que revela pistas sobre el futuro', option2Votes: 0 },
    { option1: 'Siempre poder convocar un desfile de artistas callejeros que deslumbren a la multitud', option1Votes: 0, option2: 'Siempre poder hacer que el cielo se llene de fuegos artificiales en cualquier celebración', option2Votes: 0 },
    { option1: 'Tener una escalera que te lleva a los lugares más emocionantes del mundo', option1Votes: 0, option2: 'Tener un columpio que te lleva a los paisajes más asombrosos del planeta', option2Votes: 0 },
    { option1: 'Siempre saber cómo hacer que cualquier aburrido día de trabajo se convierta en una emocionante misión', option1Votes: 0, option2: 'Siempre saber cómo hacer que cualquier reunión se convierta en una aventura inolvidable', option2Votes: 0 },
    { option1: 'Tener una máquina de burbujas que llena el aire con burbujas de colores en cualquier momento', option1Votes: 0, option2: 'Tener una máquina de confeti que convierte cualquier lugar en una fiesta instantánea', option2Votes: 0 },
    { option1: 'Siempre poder organizar una búsqueda del tesoro que emocione a todos', option1Votes: 0, option2: 'Siempre poder organizar un juego de rol que sumerja a todos en un mundo mágico', option2Votes: 0 },
    { option1: 'Tener una lupa que revela detalles mágicos ocultos en el mundo', option1Votes: 0, option2: 'Tener unos anteojos que te permiten ver a seres invisibles', option2Votes: 0 },
    { option1: 'Siempre poder encontrar el libro perfecto para cada estado de ánimo', option1Votes: 0, option2: 'Siempre poder escribir el libro perfecto para cada ocasión', option2Votes: 0 },
    { option1: 'Tener una alfombra que te lleva a lugares lejanos con solo pisarla', option1Votes: 0, option2: 'Tener un globo que te lleva a emocionantes aventuras con solo inflarlo', option2Votes: 0 },
    { option1: 'Siempre saber cómo hacer que cualquier día de lluvia se convierta en una fiesta de barro', option1Votes: 0, option2: 'Siempre saber cómo hacer que cualquier día soleado se convierta en un festival de burbujas', option2Votes: 0 },
    { option1: 'Tener un sombrero que genera chistes cómicos automáticamente', option1Votes: 0, option2: 'Tener una bufanda que te da consejos sabios en cualquier situación', option2Votes: 0 },
    { option1: 'Siempre poder convertir una caminata por el parque en una búsqueda de tesoros', option1Votes: 0, option2: 'Siempre poder convertir una visita al museo en una aventura en el tiempo', option2Votes: 0 },
    { option1: 'Tener un reloj que detiene el tiempo por un día al año para disfrutarlo a tu ritmo', option1Votes: 0, option2: 'Tener una linterna que ilumina el camino de la creatividad en la oscuridad', option2Votes: 0 },
    { option1: 'Siempre poder convertir una simple conversación en una narración épica', option1Votes: 0, option2: 'Siempre poder transformar cualquier día de la semana en el fin de semana', option2Votes: 0 },
    { option1: 'Poseer un zapato que te lleva a lugares de tus sueños', option1Votes: 0, option2: 'Poseer una llave que abre puertas a dimensiones alternativas', option2Votes: 0 },
    { option1: 'Siempre saber cómo convertir un día de limpieza en una fiesta de baile', option1Votes: 0, option2: 'Siempre saber cómo hacer que una simple cena se convierta en una experiencia gastronómica de lujo', option2Votes: 0 },
    { option1: 'Tener un paraguas que te protege de las preocupaciones y el estrés', option1Votes: 0, option2: 'Tener una mochila que siempre tiene lo que necesitas en el momento justo', option2Votes: 0 },
    { option1: 'Siempre tener la habilidad de hacer que cualquier día nublado se llene de arcoíris', option1Votes: 0, option2: 'Siempre tener la habilidad de convertir una tarde aburrida en un festival de música espontáneo', option2Votes: 0 },
    { option1: 'Poseer un espejo que refleja tus mejores momentos y te inspira a crear más', option1Votes: 0, option2: 'Poseer una caja de música que siempre toca la canción que necesitas escuchar', option2Votes: 0 },
];

export const hard = [
    { option1: 'Salvar la vida de un ser querido a costa de la tuya', option1Votes: 0, option2: 'Salvar tu vida y sacrificar la de un ser querido', option2Votes: 0 },
    { option1: 'Tener el poder de curar todas las enfermedades pero no poder curarte a ti mismo', option1Votes: 0, option2: 'Ser incapaz de curar enfermedades pero estar completamente sano', option2Votes: 0 },
    { option1: 'Poseer el conocimiento absoluto sobre el universo pero vivir una vida corta', option1Votes: 0, option2: 'Vivir una vida larga pero sin saber nada sobre el universo', option2Votes: 0 },
    { option1: 'Detener una guerra mundial pero a costa de perder a alguien cercano en el proceso', option1Votes: 0, option2: 'No intervenir en la guerra y mantener a tus seres queridos a salvo', option2Votes: 0 },
    { option1: 'Tener la habilidad de viajar en el tiempo pero sin poder cambiar el pasado', option1Votes: 0, option2: 'No poder viajar en el tiempo pero mantener el presente intacto', option2Votes: 0 },
    { option1: 'Ser capaz de detener el cambio climático pero sacrificando comodidades modernas', option1Votes: 0, option2: 'Mantener el estilo de vida actual aunque implique un futuro incierto para el planeta', option2Votes: 0 },
    { option1: 'Tener el poder de comprender y resolver todos los problemas del mundo pero sin poder compartir tus soluciones', option1Votes: 0, option2: 'No poder resolver problemas globales pero ser un líder influyente en la divulgación de soluciones', option2Votes: 0 },
    { option1: 'Ser rico pero rodeado de personas deshonestas y traicioneras', option1Votes: 0, option2: 'Ser pobre pero tener amigos leales y sinceros', option2Votes: 0 },
    { option1: 'Conocer la fecha de tu muerte pero no poder cambiarla', option1Votes: 0, option2: 'Vivir sin saber cuándo morirás', option2Votes: 0 },
    { option1: 'Tener el poder de leer los pensamientos de todos a tu alrededor pero no poder detenerlo', option1Votes: 0, option2: 'No poder leer mentes, pero mantener tu privacidad', option2Votes: 0 },
    { option1: 'Salvar a un extraño de un accidente mortal pero sufrir un accidente menos grave tú mismo', option1Votes: 0, option2: 'No intervenir y mantenerte a salvo', option2Votes: 0 },
    { option1: 'Tener la capacidad de predecir el futuro pero ser incapaz de cambiarlo', option1Votes: 0, option2: 'No tener conocimiento del futuro y vivir el presente sin influencias', option2Votes: 0 },
    { option1: 'Tener un trabajo que amas pero con un salario muy bajo', option1Votes: 0, option2: 'Tener un trabajo que odias pero con un salario muy alto', option2Votes: 0 },
    { option1: 'Ser el único ser humano en un mundo de extraterrestres amigables', option1Votes: 0, option2: 'Ser un ser humano en un mundo de extraterrestres hostiles', option2Votes: 0 },
    { option1: 'Ser inmune a todas las enfermedades pero no poder sentir emociones', option1Votes: 0, option2: 'Sentir emociones intensamente pero ser vulnerable a enfermedades', option2Votes: 0 },
    { option1: 'Poseer el conocimiento de todas las contraseñas del mundo pero no poder utilizarlo', option1Votes: 0, option2: 'No conocer ninguna contraseña y respetar la privacidad de todos', option2Votes: 0 },
    { option1: 'Salvar a una persona que ha cometido un crimen grave pero cambiar su vida para mejor', option1Votes: 0, option2: 'No intervenir y permitir que la justicia siga su curso', option2Votes: 0 },
    { option1: 'Ser un genio incomprendido pero solitario', option1Votes: 0, option2: 'Ser una persona común y encajar en la sociedad', option2Votes: 0 },
    { option1: 'Tener la capacidad de revivir a los muertos pero con consecuencias impredecibles', option1Votes: 0, option2: 'No tener ese poder y dejar que los muertos descansen en paz', option2Votes: 0 },
    { option1: 'Conocer la verdad detrás de todos los misterios del universo pero no poder compartirla', option1Votes: 0, option2: 'Vivir sin saber la verdad y mantener la curiosidad', option2Votes: 0 },
    { option1: 'Ser capaz de eliminar todos los problemas del mundo pero a costa de perder todos tus recuerdos', option1Votes: 0, option2: 'Conservar tus recuerdos y experiencias pero no poder resolver los problemas del mundo', option2Votes: 0 },
    { option1: 'Tener la capacidad de volar pero solo en sueños', option1Votes: 0, option2: 'Poder volar en la vida real, pero solo una vez al año', option2Votes: 0 },
    { option1: 'Ser testigo de un evento histórico importante pero no poder documentarlo ni contar a nadie', option1Votes: 0, option2: 'Documentar el evento, pero nadie te creerá', option2Votes: 0 },
    { option1: 'Tener el poder de cambiar el pasado y evitar un error grave pero sin garantía de un mejor futuro', option1Votes: 0, option2: 'Aceptar el error pasado y vivir con sus consecuencias', option2Votes: 0 },
    { option1: 'Poseer el don de la música pero ser sordo', option1Votes: 0, option2: 'Escuchar música hermosa pero no poder crearla', option2Votes: 0 },
    { option1: 'Ser el mejor en tu campo pero que nadie lo sepa', option1Votes: 0, option2: 'Ser el peor en tu campo pero todos piensen que eres el mejor', option2Votes: 0 },
    { option1: 'Tener la capacidad de cambiar de género a voluntad pero enfrentar la incomprensión y el prejuicio de la sociedad', option1Votes: 0, option2: 'Permanecer en tu género actual y vivir una vida más convencional', option2Votes: 0 },
    { option1: 'Conocer la fecha exacta de tu muerte y prepararte para ello', option1Votes: 0, option2: 'Vivir una vida sin conocer la fecha de tu muerte', option2Votes: 0 },
    { option1: 'Ser inmortal pero ver morir a todos tus seres queridos', option1Votes: 0, option2: 'Vivir una vida normal y experimentar la muerte de seres queridos en su tiempo', option2Votes: 0 },
    { option1: 'Poseer la riqueza y el éxito material pero carecer de amor y relaciones significativas', option1Votes: 0, option2: 'Tener relaciones amorosas significativas pero luchar financieramente', option2Votes: 0 },
    { option1: 'Ser capaz de controlar las emociones de los demás pero perder tu propia capacidad de sentir emociones', option1Votes: 0, option2: 'Mantener tus propias emociones pero no influir en las de los demás', option2Votes: 0 },
    { option1: 'Ser una persona extremadamente atractiva pero nunca ser tomado en serio', option1Votes: 0, option2: 'Ser respetado pero considerado poco atractivo', option2Votes: 0 },
    { option1: 'Poseer un poder sobrenatural pero que solo funcione cuando nadie esté mirando', option1Votes: 0, option2: 'Tener un poder sobrenatural limitado que funcione en cualquier circunstancia', option2Votes: 0 },
    { option1: 'Ser el único ser humano en un mundo de robots', option1Votes: 0, option2: 'Vivir en un mundo humano pero con la amenaza constante de la IA', option2Votes: 0 },
    { option1: 'Tener la capacidad de comunicarte con los muertos pero escuchar historias perturbadoras', option1Votes: 0, option2: 'No tener contacto con los muertos y vivir en paz', option2Votes: 0 },
    { option1: 'Ser el protagonista de tu propia película, pero sin tener privacidad', option1Votes: 0, option2: 'Vivir una vida privada pero sin ninguna historia épica', option2Votes: 0 },
    { option1: 'Tener la oportunidad de explorar el espacio exterior pero sin garantía de regresar', option1Votes: 0, option2: 'Permanecer en la Tierra y vivir una vida segura', option2Votes: 0 },
    { option1: 'Poseer un talento sobrenatural pero a costa de tu salud física', option1Votes: 0, option2: 'Tener una salud óptima pero sin talentos extraordinarios', option2Votes: 0 },
    { option1: 'Ser capaz de hablar y entender todos los idiomas pero olvidar tu lengua materna', option1Votes: 0, option2: 'Mantener tu lengua materna pero no poder comunicarte en otros idiomas', option2Votes: 0 },
    { option1: 'Tener el poder de ver el futuro de los demás pero no tu propio futuro', option1Votes: 0, option2: 'No tener visión del futuro y vivir el presente sin saber lo que sucederá', option2Votes: 0 },
    { option1: 'Poseer un objeto mágico que concede deseos pero solo uno en toda tu vida', option1Votes: 0, option2: 'No tener deseos inmediatos pero vivir una vida sin restricciones', option2Votes: 0 },
    { option1: 'Ser una celebridad mundial pero perder toda tu privacidad', option1Votes: 0, option2: 'Vivir una vida tranquila y anónima', option2Votes: 0 },
    { option1: 'Tener el don de la invisibilidad pero ser incapaz de hablar', option1Votes: 0, option2: 'Tener la habilidad de volar pero solo durante cinco minutos al día', option2Votes: 0 },
    { option1: 'Ser testigo de un acontecimiento histórico pero estar completamente solo', option1Votes: 0, option2: 'No ser testigo de la historia pero estar rodeado de seres queridos', option2Votes: 0 },
    { option1: 'Tener la capacidad de resolver cualquier misterio pero no poder compartir la solución', option1Votes: 0, option2: 'No tener la capacidad de resolver misterios pero ser un buen comunicador', option2Votes: 0 },
    { option1: 'Ser el mejor en tu campo pero siempre sentirte insatisfecho', option1Votes: 0, option2: 'Ser competente en tu campo y sentirte satisfecho con tus logros', option2Votes: 0 },
    { option1: 'Poseer el conocimiento absoluto sobre el pasado pero no poder cambiarlo', option1Votes: 0, option2: 'No conocer el pasado y vivir sin ataduras', option2Votes: 0 },
    { option1: 'Ser capaz de prevenir todas las catástrofes naturales pero a costa de la sobrepoblación', option1Votes: 0, option2: 'No interferir en las catástrofes naturales y mantener un equilibrio demográfico', option2Votes: 0 },
    { option1: 'Tener el poder de sanar cualquier herida pero absorber el dolor de la persona herida', option1Votes: 0, option2: 'No tener la capacidad de sanar heridas pero evitar el sufrimiento ajeno', option2Votes: 0 },
    { option1: 'Ser invisible pero siempre oído por todos', option1Votes: 0, option2: 'Ser completamente ignorado por todos', option2Votes: 0 },
    { option1: 'Tener el don de la persuasión pero nunca ser capaz de decir la verdad', option1Votes: 0, option2: 'Decir siempre la verdad pero nunca poder persuadir a nadie', option2Votes: 0 },
    { option1: 'Poseer una máquina del tiempo pero con un límite de 3 viajes al pasado', option1Votes: 0, option2: 'No tener acceso a una máquina del tiempo y vivir en el presente', option2Votes: 0 },
    { option1: 'Ser un maestro en todas las habilidades artísticas pero ser completamente inútil en las habilidades prácticas', option1Votes: 0, option2: 'Ser un experto en habilidades prácticas pero carecer de talento artístico', option2Votes: 0 },
    { option1: 'Tener el poder de comunicarte con extraterrestres pero ser rechazado por la humanidad', option1Votes: 0, option2: 'Ser querido por la humanidad pero incapaz de comunicarte con extraterrestres', option2Votes: 0 },
    { option1: 'Ser capaz de controlar las emociones de los demás pero ser emocionalmente inestable', option1Votes: 0, option2: 'Mantener la estabilidad emocional pero no influir en las emociones de los demás', option2Votes: 0 },
    { option1: 'Poseer el conocimiento de todas las respuestas del universo pero nunca poder formular una pregunta', option1Votes: 0, option2: 'Tener la capacidad de formular preguntas pero no tener respuestas', option2Votes: 0 },
    { option1: 'Tener la oportunidad de explorar el fondo del océano pero sin garantía de regresar', option1Votes: 0, option2: 'Permanecer en tierra firme y vivir una vida segura', option2Votes: 0 },
    { option1: 'Ser invisible pero incapaz de sentir el tacto', option1Votes: 0, option2: 'Tener sensación táctil pero ser siempre visible', option2Votes: 0 },
    { option1: 'Tener la capacidad de hablar con los animales pero que todos piensen que estás loco', option1Votes: 0, option2: 'No poder comunicarte con los animales pero ser considerado cuerdo', option2Votes: 0 },
    { option1: 'Ser un genio matemático pero incapaz de entender la música', option1Votes: 0, option2: 'Ser un músico talentoso pero no comprender las matemáticas', option2Votes: 0 },
    { option1: 'Poseer el poder de detener el tiempo pero envejecer el doble de rápido cuando lo haces', option1Votes: 0, option2: 'Envejecer a una velocidad normal y no tener el poder de detener el tiempo', option2Votes: 0 },
    { option1: 'Tener el don de la telequinesis pero solo poder mover objetos pequeños', option1Votes: 0, option2: 'No tener telequinesis y depender de la fuerza física para mover objetos', option2Votes: 0 },
    { option1: 'Ser capaz de comprender todos los idiomas del mundo pero incapaz de hablar', option1Votes: 0, option2: 'Hablar múltiples idiomas pero no entender otros', option2Votes: 0 },
    { option1: 'Poseer la riqueza de un país pero llevar el peso de la responsabilidad de dirigirlo', option1Votes: 0, option2: 'Vivir una vida sencilla sin responsabilidades políticas', option2Votes: 0 },
    { option1: 'Tener la capacidad de evitar todos los accidentes automovilísticos pero causar otros tipos de accidentes', option1Votes: 0, option2: 'No intervenir en los accidentes automovilísticos y evitar causar otros', option2Votes: 0 },
    { option1: 'Ser capaz de transformarte en cualquier animal pero sin poder elegir cuándo', option1Votes: 0, option2: 'No tener la capacidad de transformarte en animales y vivir como humano', option2Votes: 0 },
    { option1: 'Poseer la belleza perfecta pero ser percibido como superficial por todos', option1Votes: 0, option2: 'Ser apreciado por tu personalidad pero carecer de atractivo físico', option2Votes: 0 },
    { option1: 'Tener el poder de predecir desastres naturales pero sin poder evitarlos', option1Votes: 0, option2: 'No tener conocimiento de desastres naturales y vivir sin esa preocupación', option2Votes: 0 },
    { option1: 'Ser un maestro en la cocina pero nunca poder probar tus propias creaciones', option1Votes: 0, option2: 'No tener habilidades culinarias especiales y disfrutar de tus creaciones', option2Votes: 0 },
    { option1: 'Poseer el conocimiento de todos los secretos del gobierno pero no poder compartirlo', option1Votes: 0, option2: 'No conocer los secretos del gobierno y vivir sin ese conocimiento', option2Votes: 0 },
    { option1: 'Ser un gran atleta pero siempre enfrentar lesiones graves', option1Votes: 0, option2: 'Mantener una buena salud física pero no destacar en el deporte', option2Votes: 0 },
    { option1: 'Tener la capacidad de revivir a los muertos pero solo una vez en la vida', option1Votes: 0, option2: 'No poder revivir a los muertos y aceptar la muerte como parte de la vida', option2Votes: 0 },
    { option1: 'Tener el poder de ver los sueños de otras personas pero experimentar pesadillas constantes', option1Votes: 0, option2: 'No tener visiones de sueños y disfrutar de noches tranquilas', option2Votes: 0 },
    { option1: 'Ser un maestro de la meditación pero nunca poder dormir', option1Votes: 0, option2: 'Dormir cómodamente todas las noches pero nunca meditar', option2Votes: 0 },
    { option1: 'Poseer la habilidad de curar enfermedades mentales pero absorber los traumas de los pacientes', option1Votes: 0, option2: 'No poder curar enfermedades mentales y mantener tu propia salud mental', option2Votes: 0 },
    { option1: 'Tener el poder de viajar al pasado pero solo para presenciar eventos históricos sin interferir', option1Votes: 0, option2: 'No tener la capacidad de viajar en el tiempo y vivir en el presente', option2Votes: 0 },
    { option1: 'Ser capaz de predecir terremotos pero sin poder evitarlos', option1Votes: 0, option2: 'No conocer las predicciones de terremotos y vivir sin preocupaciones', option2Votes: 0 },
    { option1: 'Tener una memoria perfecta pero experimentar todos los recuerdos como si fueran nuevos', option1Votes: 0, option2: 'Mantener una memoria promedio y apreciar tus recuerdos a lo largo del tiempo', option2Votes: 0 },
    { option1: 'Ser inmune a todos los venenos pero ser alérgico a la comida', option1Votes: 0, option2: 'Disfrutar de una variedad de alimentos pero ser vulnerable a los venenos', option2Votes: 0 },
    { option1: 'Poseer el don de la telepatía pero estar constantemente bombardeado por los pensamientos de los demás', option1Votes: 0, option2: 'No tener acceso a los pensamientos de los demás y disfrutar de la privacidad mental', option2Votes: 0 },
    { option1: 'Ser la persona más inteligente del mundo pero ser socialmente inepto', option1Votes: 0, option2: 'Ser una persona sociable pero con inteligencia promedio', option2Votes: 0 },
    { option1: 'Tener la capacidad de predecir el comportamiento de las personas pero no poder cambiarlo', option1Votes: 0, option2: 'No poder predecir el comportamiento de los demás y dejar que actúen libremente', option2Votes: 0 },
    { option1: 'Ser invisible pero incapaz de ver o escuchar nada mientras lo eres', option1Votes: 0, option2: 'Tener la habilidad de ver y escuchar normalmente pero ser siempre visible', option2Votes: 0 },
    { option1: 'Poseer el conocimiento de la tecnología del futuro pero ser incapaz de compartirla con el mundo', option1Votes: 0, option2: 'No tener conocimiento de la tecnología futura y vivir en la era actual', option2Votes: 0 },
    { option1: 'Tener el poder de cambiar el clima pero con efectos impredecibles', option1Votes: 0, option2: 'No tener control sobre el clima y aceptar la naturaleza tal como es', option2Votes: 0 },
    { option1: 'Ser un prodigio musical pero perder todas las demás habilidades', option1Votes: 0, option2: 'Mantener una variedad de talentos pero carecer de habilidades musicales', option2Votes: 0 },
    { option1: 'Poseer el don de la invisibilidad pero solo durante un minuto al día', option1Votes: 0, option2: 'Ser siempre visible pero con pleno control de tus acciones', option2Votes: 0 },
    { option1: 'Tener la capacidad de leer mentes pero solo las preocupaciones y miedos de las personas', option1Votes: 0, option2: 'No poder leer mentes y experimentar comunicación verbal para entender a los demás', option2Votes: 0 },
    { option1: 'Ser un experto en resolver enigmas pero estar constantemente rodeado de misterios', option1Votes: 0, option2: 'Vivir sin la habilidad de resolver enigmas y disfrutar de una vida sin complicaciones', option2Votes: 0 },
    { option1: 'Ser capaz de hablar con los animales pero experimentar sus dolores y malestares', option1Votes: 0, option2: 'No poder comunicarte con los animales y vivir sin compartir sus sufrimientos', option2Votes: 0 },
    { option1: 'Poseer la riqueza de un país pero estar obligado a donar la mayor parte a organizaciones benéficas', option1Votes: 0, option2: 'No tener riquezas excesivas y administrar tu dinero según tu elección', option2Votes: 0 },
    { option1: 'Tener el poder de detener el tiempo pero envejecer el triple de rápido cuando lo haces', option1Votes: 0, option2: 'Envejecer a una velocidad normal y no tener el poder de detener el tiempo', option2Votes: 0 },
    { option1: 'Ser un genio de la informática pero estar bajo vigilancia constante del gobierno', option1Votes: 0, option2: 'No tener habilidades informáticas extraordinarias y vivir sin ser vigilado', option2Votes: 0 },
    { option1: 'Poseer la belleza ideal pero ser incapaz de mantener una relación amorosa', option1Votes: 0, option2: 'Tener relaciones amorosas significativas pero sin un atractivo físico excepcional', option2Votes: 0 },
    { option1: 'Tener la capacidad de ver el mundo a través de los ojos de cualquier persona pero sin control de cuándo sucede', option1Votes: 0, option2: 'Vivir tu propia vida sin experimentar la perspectiva de otros', option2Votes: 0 },
    { option1: 'Ser un líder mundial influyente pero sacrificar tu vida personal y privacidad', option1Votes: 0, option2: 'Vivir una vida privada tranquila sin la influencia de la política', option2Votes: 0 },
    { option1: 'Tener la habilidad de predecir con precisión los desastres naturales y salvar vidas, pero vivir en constante tensión', option1Votes: 0, option2: 'Vivir sin conocimiento sobre los desastres naturales y experimentar tranquilidad', option2Votes: 0 },
    { option1: 'Ser capaz de comunicarte con cualquier especie animal pero ser excluido por los humanos', option1Votes: 0, option2: 'Ser aceptado por la sociedad pero incapaz de comunicarte con animales', option2Votes: 0 },
    { option1: 'Poseer el conocimiento de todos los misterios del universo pero nunca encontrar respuestas a tus preguntas personales', option1Votes: 0, option2: 'No conocer los misterios del universo y centrarte en tus propias búsquedas de respuestas', option2Votes: 0 },
    { option1: 'Tener el poder de controlar las emociones de los demás pero causar confusión y caos en sus vidas', option1Votes: 0, option2: 'No tener influencia sobre las emociones de los demás y permitirles vivir sin interferencias', option2Votes: 0 },
    { option1: 'Ser un maestro de las artes marciales pero no poder utilizar tu habilidad para herir a otros', option1Votes: 0, option2: 'No tener habilidades de lucha excepcionales y vivir una vida sin enfrentamientos físicos', option2Votes: 0 },
    { option1: 'Poseer el don de la precognición pero experimentar visiones constantes y confusas', option1Votes: 0, option2: 'No tener visiones del futuro y vivir el presente sin distracciones', option2Votes: 0 },
];
