export const classic = [
    { id: 1, option1: 'Ser invisible', option1Votes: 0, option2: 'Ser capaz de volar', option2Votes: 0 },
    { id: 2, option1: 'Ser rico', option1Votes: 0, option2: 'Ser famoso', option2Votes: 0 },
    { id: 3, option1: 'Ser el mejor amigo de un famoso', option1Votes: 0, option2: 'Ser el peor enemigo de un famoso', option2Votes: 0 },
    { id: 4, option1: 'Ser el mejor en algo que no te gusta', option1Votes: 0, option2: 'Ser el peor en algo que te gusta', option2Votes: 0 },
    { id: 5, option1: 'Tener el poder de leer mentes', option1Votes: 0, option2: 'Tener el poder de ser invisible', option2Votes: 0 },
    { id: 6, option1: 'Ser millonario pero siempre trabajar', option1Votes: 0, option2: 'Ser pobre pero nunca tener que trabajar', option2Votes: 0 },
    { id: 7, option1: 'Viajar al pasado', option1Votes: 0, option2: 'Viajar al futuro', option2Votes: 0 },
    { id: 8, option1: 'Ser extremadamente inteligente pero no tener sentido del humor', option1Votes: 0, option2: 'Ser muy divertido pero no ser muy inteligente', option2Votes: 0 },
    { id: 9, option1: 'Tener la capacidad de volverse invisible cuando nadie te esté mirando', option1Votes: 0, option2: 'Tener la capacidad de volar pero solo a una altura máxima de 1 metro', option2Votes: 0 },
    { id: 10, option1: 'Ser siempre el centro de atención', option1Votes: 0, option2: 'Pasar desapercibido en cualquier situación', option2Votes: 0 },
    { id: 11, option1: 'Tener la capacidad de controlar el clima', option1Votes: 0, option2: 'Tener la capacidad de hablar con los animales', option2Votes: 0 },
    { id: 12, option1: 'Ser extremadamente rico pero nunca encontrar el amor verdadero', option1Votes: 0, option2: 'Encontrar el amor verdadero pero siempre tener problemas financieros', option2Votes: 0 },
    { id: 13, option1: 'Ser conocido por algo negativo pero ser millonario', option1Votes: 0, option2: 'Ser desconocido pero amado por todos', option2Votes: 0 },
    { id: 14, option1: 'Poder leer todos los libros del mundo en un instante', option1Votes: 0, option2: 'Poder hablar todos los idiomas del mundo de forma fluida', option2Votes: 0 },
    { id: 15, option1: 'Tener la capacidad de detener el tiempo', option1Votes: 0, option2: 'Tener la capacidad de viajar en el tiempo', option2Votes: 0 },
    { id: 16, option1: 'Ser el mejor en tu profesión pero odiar lo que haces', option1Votes: 0, option2: 'Hacer lo que amas pero no ser reconocido por ello', option2Votes: 0 },
    { id: 17, option1: 'Tener la capacidad de controlar los sueños', option1Votes: 0, option2: 'Tener la capacidad de controlar los pensamientos de las personas', option2Votes: 0 },
    { id: 18, option1: 'Ser un genio incomprendido', option1Votes: 0, option2: 'Ser una persona promedio pero muy feliz', option2Votes: 0 },
    { id: 19, option1: 'Ser teletransportado instantáneamente a cualquier lugar', option1Votes: 0, option2: 'Tener la capacidad de leer la mente de las personas', option2Votes: 0 },
    { id: 20, option1: 'Tener la capacidad de hablar con los animales', option1Votes: 0, option2: 'Tener la capacidad de hablar todos los idiomas del mundo', option2Votes: 0 },
    { id: 21, option1: 'Ser capaz de ver 10 minutos en el futuro', option1Votes: 0, option2: 'Ser capaz de ver 150 años en el futuro', option2Votes: 0 },
    { id: 22, option1: 'Ser el mejor jugador de videojuegos del mundo', option1Votes: 0, option2: 'Ser el mejor deportista en tu deporte favorito', option2Votes: 0 },
    { id: 23, option1: 'Tener la capacidad de detener el envejecimiento', option1Votes: 0, option2: 'Tener la capacidad de curar cualquier enfermedad', option2Votes: 0 },
    { id: 24, option1: 'Poder dormir con solo chasquear los dedos', option1Votes: 0, option2: 'Volver a ver tus sueños en un video', option2Votes: 0 },
    { id: 25, option1: 'Ser un experto en todas las artes marciales', option1Votes: 0, option2: 'Ser un maestro en todas las disciplinas musicales', option2Votes: 0 },
    { id: 26, option1: 'Ser abducido por extraterrestres', option1Votes: 0, option2: 'Ser poseído por un demonio', option2Votes: 0 },
    { id: 27, option1: 'Poder congelar el tiempo cuando estás en peligro', option1Votes: 0, option2: 'Poder retroceder el tiempo cuando estás en peligro', option2Votes: 0 },
    { id: 28, option1: 'Ser el personaje principal de tu videojuego favorito', option1Votes: 0, option2: 'Ser el personaje principal de tu película favorita', option2Votes: 0 },
    { id: 29, option1: 'Ser capaz de congelar el agua con solo tocarla', option1Votes: 0, option2: 'Ser capaz de hervir el agua con solo tocarla', option2Votes: 0 },
    { id: 30, option1: 'Que te paguen por cada libro que lees', option1Votes: 0, option2: 'Que te paguen por cada película que ves', option2Votes: 0 },
    { id: 31, option1: 'Ser invisible pero hacer un sonido fuerte cada vez que te mueves', option1Votes: 0, option2: 'Ser capaz de volar pero solo a baja velocidad', option2Votes: 0 },
    { id: 32, option1: 'Ser el mejor chef del mundo', option1Votes: 0, option2: 'Ser el mejor músico del mundo', option2Votes: 0 },
    { id: 33, option1: 'Tener la capacidad de predecir el futuro', option1Votes: 0, option2: 'Tener la capacidad de cambiar el pasado', option2Votes: 0 },
    { id: 34, option1: 'Ser inmune a todas las enfermedades', option1Votes: 0, option2: 'Tener una increíble resistencia física', option2Votes: 0 },
    { id: 35, option1: 'Vivir un año extra cada vez que besas a alguien', option1Votes: 0, option2: 'Vivir un año extra cada vez que abrazas a alguien', option2Votes: 0 },
    { id: 36, option1: 'Tener siempre frio', option1Votes: 0, option2: 'Tener siempre calor', option2Votes: 0 },
    { id: 37, option1: 'Ser capaz de leer los labios', option1Votes: 0, option2: 'Entender el lenguaje de señas', option2Votes: 0 },
    { id: 38, option1: 'Tener la capacidad de regresar en el tiempo y corregir tus errores', option1Votes: 0, option2: 'Tener la capacidad de ver el futuro y saber qué decisiones tomar', option2Votes: 0 },
    { id: 39, option1: 'Tener la capacidad de hacer realidad cualquier deseo tuyo', option1Votes: 0, option2: 'Tener la capacidad de hacer realidad cualquier deseo de los demás', option2Votes: 0 },
    { id: 40, option1: 'Ser conocido por haber descubierto una cura para una enfermedad mortal', option1Votes: 0, option2: 'Ser conocido por haber inventado una tecnología revolucionaria', option2Votes: 0 },
    { id: 41, option1: 'Siempre tener que hablar en rima', option1Votes: 0, option2: 'Siempre tener que cantar lo que dices', option2Votes: 0 },
    { id: 42, option1: 'Siempre tener que moverte como un robot', option1Votes: 0, option2: 'Siempre tener que moverte como un animal', option2Votes: 0 },
    { id: 43, option1: 'Tener siempre una melodía pegajosa en la cabeza', option1Votes: 0, option2: 'Nunca más poder escuchar música', option2Votes: 0 },
    { id: 44, option1: 'Comer pizza todos los días', option1Votes: 0, option2: 'Comer helado todos los días', option2Votes: 0 },
    { id: 45, option1: 'Tener una conversación solo en memes', option1Votes: 0, option2: 'Tener una conversación solo en emojis', option2Votes: 0 },
    { id: 46, option1: 'Siempre tener que contar chistes malos', option1Votes: 0, option2: 'Nunca más poder escuchar un chiste', option2Votes: 0 },
    { id: 47, option1: 'Tener una mascota dinosaurio', option1Votes: 0, option2: 'Tener una mascota dragón', option2Votes: 0 },
    { id: 48, option1: 'Siempre tener que bailar cuando escuchas música', option1Votes: 0, option2: 'Siempre tener que hacer muecas cuando hablas', option2Votes: 0 },
    { id: 49, option1: 'Usar calcetines con agujeros', option1Votes: 0, option2: 'Usar zapatos que aprietan', option2Votes: 0 },
    { id: 50, option1: 'Escuchar siempre la misma canción', option1Votes: 0, option2: 'Ver siempre la misma película', option2Votes: 0 },
    { id: 51, option1: 'Siempre tener que andar en bicicleta para moverte', option1Votes: 0, option2: 'Siempre tener que andar en patines para moverte', option2Votes: 0 },
    { id: 52, option1: 'Tener un clon de ti que haga todas las tareas aburridas', option1Votes: 0, option2: 'Tener un clon de ti que haga todo el trabajo duro', option2Votes: 0 },
    { id: 53, option1: 'Siempre tener un fondo musical en tu vida', option1Votes: 0, option2: 'Siempre tener una audiencia que aplaude después de cada cosa que haces', option2Votes: 0 },
    { id: 54, option1: 'Ser Iron Man pero siempre tener que usar el traje', option1Votes: 0, option2: 'Ser Hulk pero siempre tener que estar enojado', option2Votes: 0 },
    { id: 55, option1: 'Tener un teléfono que solo pueda enviar gifs', option1Votes: 0, option2: 'Tener un teléfono que solo pueda enviar memes', option2Votes: 0 },
    { id: 56, option1: 'Siempre tener que usar un sombrero extravagante', option1Votes: 0, option2: 'Siempre tener que usar zapatos que suenan con cada paso', option2Votes: 0 },
    { id: 57, option1: 'Vivir en el fondo del mar', option1Votes: 0, option2: 'Vivir en el espacio', option2Votes: 0 },
    { id: 58, option1: 'Tener la capacidad de cambiar de color como un camaleón', option1Votes: 0, option2: 'Tener la capacidad de brillar en la oscuridad como una luciérnaga', option2Votes: 0 },
    { id: 59, option1: 'Siempre tener que moverte haciendo moonwalk', option1Votes: 0, option2: 'Siempre tener que moverte como si estuvieras en una pasarela', option2Votes: 0 },
    { id: 60, option1: 'Tener la capacidad de entender los pensamientos de tu gato', option1Votes: 0, option2: 'Tener la capacidad de entender los pensamientos de tu perro', option2Votes: 0 },
    { id: 61, option1: 'Siempre tener una canción de fondo cuando hablas', option1Votes: 0, option2: 'Nunca más poder escuchar tu voz', option2Votes: 0 },
    { id: 62, option1: 'No poder usar tu teléfono por un mes', option1Votes: 0, option2: 'No poder usar tu computadora por un mes', option2Votes: 0 },
    { id: 63, option1: 'No poder dormir por una semana', option1Votes: 0, option2: 'No poder comer por una semana', option2Votes: 0 },
    { id: 64, option1: 'Tener la capacidad de transformar cualquier objeto en una versión miniatura', option1Votes: 0, option2: 'Tener la capacidad de transformar cualquier objeto en una versión gigante', option2Votes: 0 },
    { id: 65, option1: 'Siempre tener que saludar a las personas con un saludo inventado', option1Votes: 0, option2: 'Siempre tener que saludar a las personas con un baile improvisado', option2Votes: 0 },
    { id: 66, option1: 'Tener la capacidad de hacer que las cosas se iluminen al tocarlas', option1Votes: 0, option2: 'Tener la capacidad de hacer que las cosas desaparezcan al tocarlas', option2Votes: 0 },
    { id: 67, option1: 'Siempre tener que hablar usando solo rimas', option1Votes: 0, option2: 'Siempre tener que hablar con palabras inventadas por ti', option2Votes: 0 },
    { id: 68, option1: 'Tener super fuerza como Hulk', option1Votes: 0, option2: 'Tener super velocidad como Flash', option2Votes: 0 },
    { id: 69, option1: 'Siempre tener que hablar con voz de bebé', option1Votes: 0, option2: 'Siempre tener que hablar con voz de anciano', option2Votes: 0 },
    { id: 70, option1: 'Siempre tener que hablar muy fuerte', option1Votes: 0, option2: 'Siempre tener que hablar muy bajo', option2Votes: 0 },
    { id: 71, option1: 'Tener un viaje gratis a cualquier lugar del mundo cada año', option1Votes: 0, option2: 'Tener un encuentro con tu celebridad favorita una vez en tu vida', option2Votes: 0 },
    { id: 72, option1: 'Siempre tener que llevar un disfraz extravagante en público', option1Votes: 0, option2: 'Siempre tener que llevar ropa al revés en público', option2Votes: 0 },
    { id: 73, option1: 'Tener la capacidad de saber el nombre de cualquier persona que veas', option1Votes: 0, option2: 'Tener la capacidad de saber la edad de cualquier persona que veas', option2Votes: 0 },
    { id: 74, option1: 'Ser un personaje de Dragon Ball', option1Votes: 0, option2: 'Ser un personaje de Naruto', option2Votes: 0 },
    { id: 75, option1: 'Tener un baúl que siempre contiene exactamente lo que necesitas', option1Votes: 0, option2: 'Tener un espejo que te muestra cómo serás en 20 años', option2Votes: 0 },
    { id: 76, option1: 'Siempre estar enojado', option1Votes: 0, option2: 'Siempre estar triste', option2Votes: 0 },
    { id: 77, option1: 'No poder dormir temprano', option1Votes: 0, option2: 'No poder despertar temprano', option2Votes: 0 },
    { id: 78, option1: 'Siempre tener que hablar en acertijos', option1Votes: 0, option2: 'Siempre tener que hablar en trabalenguas', option2Votes: 0 },
    { id: 79, option1: 'Ser aprueba de balas', option1Votes: 0, option2: 'Ser aprueba de fuego', option2Votes: 0 },
    { id: 80, option1: 'Siempre tener que correr en cámara lenta', option1Votes: 0, option2: 'Siempre tener que hablar en cámara lenta', option2Votes: 0 },
    { id: 81, option1: 'Mudarte de casa cada 3 meses', option1Votes: 0, option2: 'Mudarte de país cada 3 años', option2Votes: 0 },
    { id: 82, option1: 'No festejar tu cumpleaños nunca más', option1Votes: 0, option2: 'No celebrar navidad nunca más', option2Votes: 0 },
    { id: 83, option1: 'No tener que lavarte los dientes nunca más', option1Votes: 0, option2: 'No tener que bañarte nunca más', option2Votes: 0 },
    { id: 84, option1: 'Saber cuando morirás', option1Votes: 0, option2: 'Saber cómo morirás', option2Votes: 0 },
    { id: 85, option1: 'Siempre tener que comunicarte en lenguaje de señas', option1Votes: 0, option2: 'Siempre tener que comunicarte en lenguaje morse', option2Votes: 0 },
    { id: 86, option1: 'Siempre tener comezón', option1Votes: 0, option2: 'Siempre tener hipo', option2Votes: 0 },
    { id: 87, option1: 'Siempre tener que hacer una reverencia al saludar a alguien', option1Votes: 0, option2: 'Siempre tener que hacer una pirueta al saludar a alguien', option2Votes: 0 },
    { id: 88, option1: 'Tener un Lamborghini', option1Votes: 0, option2: 'Tener un Ferrari', option2Votes: 0 },
    { id: 89, option1: 'Ser un Super Saiyajin fase 4', option1Votes: 0, option2: 'Ser un Super Saiyajin fase Dios', option2Votes: 0 },
    { id: 90, option1: 'Siempre tener que contar un chiste antes de hablar en serio', option1Votes: 0, option2: 'Siempre tener que contar un hecho interesante antes de hablar en serio', option2Votes: 0 },
    { id: 91, option1: 'Ser Spider-Man', option1Votes: 0, option2: 'Ser Batman', option2Votes: 0 },
    { id: 92, option1: 'Siempre tener que bailar en cualquier lugar donde escuches música', option1Votes: 0, option2: 'Siempre tener que hacer un chiste cada vez que alguien hable contigo', option2Votes: 0 },
    { id: 93, option1: 'Tener un control remoto que funcione solo en personas', option1Votes: 0, option2: 'Tener un control remoto que funcione solo en objetos', option2Votes: 0 },
    { id: 94, option1: 'Siempre tener que hablar sarcásticamente', option1Votes: 0, option2: 'Siempre tener que hablar en tono cómico', option2Votes: 0 },
    { id: 95, option1: 'Siempre encontrar un cabello en tu comida', option1Votes: 0, option2: 'Siempre encontrar un insecto en tu comida', option2Votes: 0 },
    { id: 96, option1: 'Siempre tener que llevar un bigote falso', option1Votes: 0, option2: 'Siempre tener que llevar una nariz roja de payaso', option2Votes: 0 },
    { id: 97, option1: 'Siempre estar sentado', option1Votes: 0, option2: 'Siempre estar de pie', option2Votes: 0 },
    { id: 98, option1: 'Siempre tener un brazo levantado', option1Votes: 0, option2: 'Siempre tener un ojo cerrado', option2Votes: 0 },
    { id: 99, option1: 'Vivir en la Antártida', option1Votes: 0, option2: 'Vivir en el Sahara', option2Votes: 0 },
    { id: 100, option1: 'Siempre tener que moverte en cámara lenta cuando estás emocionado', option1Votes: 0, option2: 'Siempre tener que moverte muy rápido cuando estás nervioso', option2Votes: 0 },
    { id: 101, option1: 'Siempre tener tus manos pegajosas', option1Votes: 0, option2: 'Siempre tener tus pies pegajosos', option2Votes: 0 },
    { id: 102, option1: 'Siempre tener que hablar con voz de robot', option1Votes: 0, option2: 'Siempre tener que hablar con voz de caricatura', option2Votes: 0 },
    { id: 103, option1: 'Aparecer en una película de Marvel', option1Votes: 0, option2: 'Aparecer en una película de DC', option2Votes: 0 },
    { id: 104, option1: 'Ser calvo', option1Votes: 0, option2: 'Tener el pelo muy largo', option2Votes: 0 },
    { id: 105, option1: 'Tener 1 millón de suscriptores en YouTube', option1Votes: 0, option2: 'Tener 1 millón de seguidores en Instagram', option2Votes: 0 },
    { id: 106, option1: 'Siempre tener un séquito de pingüinos siguiéndote', option1Votes: 0, option2: 'Siempre tener un séquito de flamencos siguiéndote', option2Votes: 0 },
    { id: 107, option1: 'Siempre llegar con 2 horas de anticipación a cualquier lugar', option1Votes: 0, option2: 'Siempre llegar 2 horas tarde a cualquier lugar', option2Votes: 0 },
    { id: 108, option1: 'Olvidar quién eres', option1Votes: 0, option2: 'Olvidar quiénes son los demás', option2Votes: 0 },
    { id: 109, option1: 'Nunca poder quejarte', option1Votes: 0, option2: 'Nunca poder decir gracias', option2Votes: 0 },
    { id: 110, option1: 'Ser policía', option1Votes: 0, option2: 'Ser bombero', option2Votes: 0 },
    { id: 111, option1: 'Tener siempre un acompañante invisible que solo tú puedes ver', option1Votes: 0, option2: 'Tener siempre una sombra que tiene su propia personalidad', option2Votes: 0 },
    { id: 112, option1: 'Tener la capacidad de hacer que las nubes formen figuras específicas', option1Votes: 0, option2: 'Tener la capacidad de cambiar el color del cielo a voluntad', option2Votes: 0 },
    { id: 113, option1: 'Tener la capacidad de cambiar el sabor de cualquier comida a tu antojo', option1Votes: 0, option2: 'Tener la capacidad de cambiar el olor de cualquier ambiente a tu antojo', option2Votes: 0 },
    { id: 114, option1: 'Siempre tener que andar de puntillas', option1Votes: 0, option2: 'Siempre tener que andar en un solo pie', option2Votes: 0 },
    { id: 115, option1: 'Siempre tener que contar tus pensamientos en voz alta', option1Votes: 0, option2: 'Siempre tener que hablar en un idioma inventado por ti', option2Votes: 0 },
    { id: 116, option1: 'Siempre tener que hacer una pausa larga antes de responder cualquier pregunta', option1Votes: 0, option2: 'Siempre tener que responder instantáneamente sin pensar', option2Votes: 0 },
    { id: 117, option1: 'Tener la capacidad de cambiar la voz de las personas a tu antojo', option1Votes: 0, option2: 'Tener la capacidad de cambiar el acento de las personas a tu antojo', option2Votes: 0 },
    { id: 118, option1: 'Siempre tener que llevar una cola de sirena en lugar de piernas', option1Votes: 0, option2: 'Siempre tener que llevar orejas de conejo en lugar de orejas humanas', option2Votes: 0 },
    { id: 119, option1: 'Siempre tener que usar gafas de sol, incluso en interiores', option1Votes: 0, option2: 'Siempre tener que llevar un paraguas, incluso en días soleados', option2Votes: 0 },
    { id: 120, option1: 'Siempre tener que llevar un globo atado a tu muñeca', option1Votes: 0, option2: 'Siempre tener que llevar una campana que suene al caminar', option2Votes: 0 },
    { id: 121, option1: 'Ser dueño de un Lamborghini', option1Votes: 0, option2: 'Poseer una lujosa mansión', option2Votes: 0 },
    { id: 122, option1: 'Ser un médico exitoso', option1Votes: 0, option2: 'Ser un abogado respetado', option2Votes: 0 },
    { id: 123, option1: 'Tener un trabajo que te permita viajar por el mundo', option1Votes: 0, option2: 'Tener un trabajo bien remunerado cerca de casa', option2Votes: 0 },
    { id: 124, option1: 'Vivir en una gran ciudad con una carrera exitosa', option1Votes: 0, option2: 'Vivir en un pueblo tranquilo con una vida sencilla', option2Votes: 0 },
    { id: 125, option1: 'Trabajar en una empresa tecnológica innovadora', option1Votes: 0, option2: 'Administrar tu propio negocio con éxito', option2Votes: 0 },
    { id: 126, option1: 'Poseer una colección de coches clásicos', option1Votes: 0, option2: 'Tener un guardarropa con ropa de diseñador', option2Votes: 0 },
    { id: 127, option1: 'Ser un atleta profesional famoso', option1Votes: 0, option2: 'Ser un músico talentoso y reconocido', option2Votes: 0 },
    { id: 128, option1: 'Ser dueño de tu propio restaurante', option1Votes: 0, option2: 'Dirigir una empresa de tecnología exitosa', option2Votes: 0 },
    { id: 129, option1: 'Trabajar como bombero', option1Votes: 0, option2: 'Trabajar como astronauta', option2Votes: 0 },
    { id: 130, option1: 'Vivir en una casa en la playa con vistas al mar', option1Votes: 0, option2: 'Vivir en una casa en las montañas con aire fresco', option2Votes: 0 },
    { id: 131, option1: 'Dedicarte a la música y ser un músico reconocido', option1Votes: 0, option2: 'Ser un deportista profesional y competir en los Juegos Olímpicos', option2Votes: 0 },
    { id: 132, option1: 'Trabajar en Amazon', option1Votes: 0, option2: 'Trabajar en Google', option2Votes: 0 },
    { id: 133, option1: 'Ser astronauta de la NASA', option1Votes: 0, option2: 'Ser piloto de Fórmula 1', option2Votes: 0 },
    { id: 134, option1: 'Ser director de cine en Hollywood', option1Votes: 0, option2: 'Ser protagonista de una película de Hollywood', option2Votes: 0 },
    { id: 135, option1: 'Ser chef en un restaurante con estrellas Michelin', option1Votes: 0, option2: 'Ser crítico de comida de renombre', option2Votes: 0 },
    { id: 136, option1: 'Que no exista la pobreza', option1Votes: 0, option2: 'Que no exista la guerra', option2Votes: 0 },
    { id: 137, option1: 'Que no exista Apple', option1Votes: 0, option2: 'Que no exista Microsoft', option2Votes: 0 },
    { id: 138, option1: 'Xbox', option1Votes: 0, option2: 'PlayStation', option2Votes: 0 },
    { id: 139, option1: 'Ser un personaje de Marvel', option1Votes: 0, option2: 'Ser un personaje de DC', option2Votes: 0 },
    { id: 140, option1: 'No poder pronunciar la letra "R"', option1Votes: 0, option2: 'No poder pronunciar la letra "L"', option2Votes: 0 },
    { id: 141, option1: 'Que no exista la música', option1Votes: 0, option2: 'Que no exista el cine', option2Votes: 0 },
    { id: 142, option1: 'Que no exista la televisión', option1Votes: 0, option2: 'Que no exista Internet', option2Votes: 0 },
    { id: 143, option1: 'Android', option1Votes: 0, option2: 'iOS', option2Votes: 0 },
];

export const hard = [
    { id: 1, option1: 'Salvar la vida de un ser querido a costa de la tuya', option1Votes: 0, option2: 'Salvar tu vida y sacrificar la de un ser querido', option2Votes: 0 },
    { id: 2, option1: 'Tener el poder de curar todas las enfermedades pero no poder curarte a ti mismo', option1Votes: 0, option2: 'Tener el poder de curarte a ti mismo pero no poder curar a nadie más', option2Votes: 0 },
    { id: 3, option1: 'Ser rico pero rodeado de personas deshonestas y traicioneras', option1Votes: 0, option2: 'Ser pobre pero tener amigos leales y sinceros', option2Votes: 0 },
    { id: 4, option1: 'Tener la capacidad de predecir el futuro pero ser incapaz de cambiarlo', option1Votes: 0, option2: 'Poder cambiar tu futuro pero causar algo malo a alguien que amas', option2Votes: 0 },
    { id: 5, option1: 'Tener un trabajo que amas pero con un salario muy bajo', option1Votes: 0, option2: 'Tener un trabajo que odias pero con un salario muy alto', option2Votes: 0 },
    { id: 6, option1: 'Ser inmune a todas las enfermedades pero no poder sentir emociones', option1Votes: 0, option2: 'Sentir emociones intensamente pero ser vulnerable a enfermedades', option2Votes: 0 },
    { id: 7, option1: 'Poseer el don de la música pero ser sordo', option1Votes: 0, option2: 'Ser capaz de pintar obras maestras pero ser ciego', option2Votes: 0 },
    { id: 8, option1: 'Poseer la riqueza y el éxito material pero carecer de amor y relaciones significativas', option1Votes: 0, option2: 'Tener relaciones amorosas significativas pero luchar financieramente', option2Votes: 0 },
    { id: 9, option1: 'Ser capaz de controlar las emociones de los demás pero perder tu propia capacidad de sentir emociones', option1Votes: 0, option2: 'No poder controlar tus propias emociones sin importar lo que suceda', option2Votes: 0 },
    { id: 10, option1: 'Ser una persona extremadamente atractiva pero nunca ser tomado en serio', option1Votes: 0, option2: 'Ser respetado pero considerado poco atractivo', option2Votes: 0 },
    { id: 11, option1: 'Tener la oportunidad de explorar el espacio exterior pero sin garantía de regresar', option1Votes: 0, option2: 'Explorar el fondo del océano pero sin garantía de regresar', option2Votes: 0 },
    { id: 12, option1: 'Poseer un talento sobrenatural pero a costa de tu salud física', option1Votes: 0, option2: 'Tener una salud física perfecta pero ser completamente inutil', option2Votes: 0 },
    { id: 13, option1: 'Ser capaz de hablar y entender todos los idiomas pero olvidar tu lengua materna', option1Votes: 0, option2: 'Mantener tu lengua materna pero no poder aprender ningún otro idioma', option2Votes: 0 },
    { id: 14, option1: 'Ser un genio matemático pero incapaz de entender la música', option1Votes: 0, option2: 'Ser un músico talentoso pero incapaz de entender las matemáticas', option2Votes: 0 },
    { id: 15, option1: 'Envejecer el doble de rápido', option1Votes: 0, option2: 'Envejecer la mitad de rápido', option2Votes: 0 },
    { id: 16, option1: 'Poseer la riqueza de un país pero llevar el peso de la responsabilidad de dirigirlo', option1Votes: 0, option2: 'Vivir en un país con pobreza sin tener la responsabilidad de dirigirlo', option2Votes: 0 },
    { id: 17, option1: 'Ser capaz de transformarte en cualquier animal pero sin poder elegir cuándo', option1Votes: 0, option2: 'Ser capaz de transformarte en cualquier persona pero sin poder elegir cuándo', option2Votes: 0 },
    { id: 18, option1: 'Experimentar pesadillas constantes', option1Votes: 0, option2: 'Experimentar alucinaciones constantes', option2Votes: 0 },
    { id: 19, option1: 'Tener el don de la persuasión pero nunca ser capaz de decir la verdad', option1Votes: 0, option2: 'Decir siempre la verdad pero nunca poder persuadir a nadie', option2Votes: 0 },
    { id: 20, option1: 'Ser responsable de la muerte de una persona inocente', option1Votes: 0, option2: 'Ser responsable de la muerte de diez gatitos indefensos', option2Votes: 0 },
    { id: 21, option1: 'Estar atrapado en un incendio forestal', option1Votes: 0, option2: 'Estar atrapado en un submarino que se hunde', option2Votes: 0 },
    { id: 22, option1: 'Perder a todos tus seres queridos', option1Votes: 0, option2: 'Ser odiado por todos tus seres queridos', option2Votes: 0 },
    { id: 23, option1: 'Perder la capacidad de hablar', option1Votes: 0, option2: 'Tener que decir todo lo que piensas sin filtro', option2Votes: 0 },
    { id: 24, option1: 'Vivir solo en una isla desierta', option1Votes: 0, option2: 'Vivir en una ciudad superpoblada sin privacidad', option2Votes: 0 },
    { id: 25, option1: 'Perder un brazo', option1Votes: 0, option2: 'Perder la vista', option2Votes: 0 },
    { id: 26, option1: 'Estar siempre con hambre', option1Votes: 0, option2: 'Estar siempre cansado', option2Votes: 0 },
    { id: 27, option1: 'Vivir sin internet por el resto de tu vida', option1Votes: 0, option2: 'Tener que renunciar a todas tus posesiones materiales', option2Votes: 0 },
    { id: 28, option1: 'Ser perseguido por un depredador durante un día', option1Votes: 0, option2: 'Estar perdido en un desierto sin agua durante un día', option2Votes: 0 },
    { id: 29, option1: 'No tener amigos', option1Votes: 0, option2: 'Tener amigos que te traicionen constantemente', option2Votes: 0 },
    { id: 30, option1: 'Ser enterrado vivo', option1Votes: 0, option2: 'Ser lanzado al vacío desde un gran altura', option2Votes: 0 },
    { id: 31, option1: 'Morder una cebolla cruda', option1Votes: 0, option2: 'Beber un vaso de jugo de limón concentrado', option2Votes: 0 },
    { id: 32, option1: 'Ser invisible pero incapaz de interactuar con el mundo', option1Votes: 0, option2: 'Ser visible pero siempre observado', option2Votes: 0 },
    { id: 33, option1: 'Siempre sentirte físicamente incómodo', option1Votes: 0, option2: 'Siempre sentirte emocionalmente inestable', option2Votes: 0 },
    { id: 34, option1: 'Estar atrapado en un elevador durante 24 horas', option1Votes: 0, option2: 'Estar atrapado en un avión durante 24 horas', option2Votes: 0 },
    { id: 35, option1: 'Ser completamente alérgico a la luz del sol', option1Votes: 0, option2: 'Ser completamente alérgico al agua', option2Votes: 0 },
    { id: 36, option1: 'Tener siempre el olor corporal más desagradable', option1Votes: 0, option2: 'Poder oler solo cosas desagradables', option2Votes: 0 },
    { id: 37, option1: 'Perder la capacidad de reír', option1Votes: 0, option2: 'Reír de manera incontrolable en momentos inapropiados', option2Votes: 0 },
    { id: 38, option1: 'Siempre tener sueño pero no poder dormir', option1Votes: 0, option2: 'Estar completamente despierto pero incapaz de descansar', option2Votes: 0 },
    { id: 39, option1: 'Estar atrapado en un ciclo de pesadillas sin fin', option1Votes: 0, option2: 'No poder soñar nunca más', option2Votes: 0 },
    { id: 40, option1: 'Vivir con un zumbido constante en tus oídos', option1Votes: 0, option2: 'Perder la audición por completo', option2Votes: 0 },
    { id: 41, option1: 'Siempre sentirte observado, incluso cuando estás solo', option1Votes: 0, option2: 'Nunca sentirte seguro, sin importar la situación', option2Votes: 0 },
    { id: 42, option1: 'Ser la persona más odiada en internet', option1Votes: 0, option2: 'Ser completamente desconocido y sin impacto en línea', option2Votes: 0 },
    { id: 43, option1: 'Vivir con la sensación de que algo te persigue constantemente', option1Votes: 0, option2: 'Vivir con la sensación de que siempre estás persiguiendo algo', option2Votes: 0 },
    { id: 44, option1: 'Tener la habilidad de leer los pensamientos, pero solo los pensamientos negativos sobre ti', option1Votes: 0, option2: 'No tener la habilidad de leer los pensamientos, pero que todos los demás puedan leer tus pensamientos negativos sobre ellos', option2Votes: 0 },
    { id: 45, option1: 'Estar condenado a repetir tu peor día una y otra vez', option1Votes: 0, option2: 'No poder recordar ninguno de tus días pasados', option2Votes: 0 },
    { id: 46, option1: 'Vivir en un mundo donde cada paso que das causa un desastre natural', option1Votes: 0, option2: 'Vivir en un mundo donde los desastres naturales son comunes pero aleatorios', option2Votes: 0 },
    { id: 47, option1: 'Siempre decir la verdad sin importar las consecuencias', option1Votes: 0, option2: 'Siempre mentir sin importar las consecuencias', option2Votes: 0 },
    { id: 48, option1: 'Tener una relación perfecta pero que dure solo un año', option1Votes: 0, option2: 'Tener una relación inestable pero que dure toda la vida', option2Votes: 0 },
    { id: 49, option1: 'Perder a un ser querido en un accidente que pudiste evitar', option1Votes: 0, option2: 'Causar un accidente que resulte en la pérdida de un ser querido', option2Votes: 0 },
    { id: 50, option1: 'Estar atrapado en un lugar oscuro y estrecho durante horas', option1Votes: 0, option2: 'Estar atrapado en un lugar lleno de arañas no venenosas durante minutos', option2Votes: 0 },
    { id: 51, option1: 'Sobrevivir a un naufragio en una isla desierta pero estar solo de por vida', option1Votes: 0, option2: 'Morir en el naufragio y evitar la soledad eterna', option2Votes: 0 },
    { id: 52, option1: 'Ver a tu mejor amigo sufrir una pena inmensa y no poder consolarlo', option1Votes: 0, option2: 'Sufrir tú una pena inmensa y no tener a nadie que te consuele', option2Votes: 0 },
    { id: 53, option1: 'Ser el único testigo de un crimen atroz y vivir con miedo constante', option1Votes: 0, option2: 'Ser el perpetrador de un crimen atroz y vivir con remordimiento constante', option2Votes: 0 },
    { id: 54, option1: 'Estar atrapado en un ascensor con una persona violenta', option1Votes: 0, option2: 'Estar atrapado en un ascensor con una persona enferma y contagiosa', option2Votes: 0 },
    { id: 55, option1: 'Ser la razón de la ruina financiera de tu mejor amigo', option1Votes: 0, option2: 'Perder todo tu dinero debido a la mala decisión de tu mejor amigo', option2Votes: 0 },
    { id: 56, option1: 'Descubrir que todos tus recuerdos felices fueron manipulados y falsos', option1Votes: 0, option2: 'Perder la capacidad de crear nuevos recuerdos felices', option2Votes: 0 },
    { id: 57, option1: 'Ser inmortal pero ver a todos tus seres queridos morir a tu alrededor', option1Votes: 0, option2: 'Vivir una vida donde todos tus seres queridos te consideren un extraño', option2Votes: 0 },
    { id: 58, option1: 'Vivir una vida sin amor pero llena de éxito profesional', option1Votes: 0, option2: 'Vivir una vida llena de amor pero sin éxito profesional', option2Votes: 0 },
    { id: 59, option1: 'Poseer el conocimiento de cómo y cuándo morirás', option1Votes: 0, option2: 'Poseer el conocimiento de cómo y cuándo morirá un ser querido', option2Votes: 0 },
    { id: 60, option1: 'Poseer el poder de leer los pensamientos pero no poder controlarlo', option1Votes: 0, option2: 'Que todos puedan leer tus pensamientos sin que puedas controlarlo', option2Votes: 0 },
    { id: 61, option1: 'Ser el último humano en la Tierra después de un apocalipsis', option1Votes: 0, option2: 'Ser el primero en morir durante un apocalipsis', option2Votes: 0 },
    { id: 62, option1: 'Poseer un gran poder y responsabilidad, pero vivir bajo una constante presión', option1Votes: 0, option2: 'Vivir sin responsabilidad y sin el poder de cambiar nada', option2Votes: 0 },
    { id: 63, option1: 'Tener que comer todos tus alimentos con los dedos de los pies', option1Votes: 0, option2: 'Tener que comer todos tus alimentos con las manos atadas', option2Votes: 0 },
    { id: 64, option1: 'Tener uñas permanentemente extra largas', option1Votes: 0, option2: 'Tener un solo pelo muy largo que crece constantemente desde la nariz', option2Votes: 0 },
    { id: 65, option1: 'Ver en blanco y negro', option1Votes: 0, option2: 'Tener visión borrosa', option2Votes: 0 },
    { id: 66, option1: 'Siempre tener tus manos pegajosas', option1Votes: 0, option2: 'Siempre sentir que tienes arena en los ojos', option2Votes: 0 },
    { id: 67, option1: 'Ser atacado por un pato furioso', option1Votes: 0, option2: 'Ser atacado por un zorrillo apestoso', option2Votes: 0 },
    { id: 68, option1: 'Tener un tatuaje permanente en la frente con el nombre de tu peor enemigo', option1Votes: 0, option2: 'Tener un tatuaje permanente en la frente con un insulto hacia ti mismo', option2Votes: 0 },
    { id: 69, option1: 'Siempre sentir la sensación de que una araña te camina por el brazo', option1Votes: 0, option2: 'Sentir una descarga eléctrica pequeña cada vez que dices una mentira', option2Votes: 0 },
    { id: 70, option1: 'Tener que comer tu comida sin usar utensilios', option1Votes: 0, option2: 'Tener que beber todas tus bebidas a través de un embudo', option2Votes: 0 },
    { id: 71, option1: 'Despertar cada mañana con un peinado ridículo que no puedes arreglar', option1Votes: 0, option2: 'Despertar cada mañana con un nuevo corte de pelo que no puedes cambiar', option2Votes: 0 },
    { id: 72, option1: 'Tener la risa más irritante del mundo', option1Votes: 0, option2: 'Decir "xd" después de cada oración', option2Votes: 0 },
    { id: 73, option1: 'Siempre tener los calcetines húmedos', option1Votes: 0, option2: 'Tener zapatos que chillan en cada paso', option2Votes: 0 },
    { id: 74, option1: 'Tener una araña del tamaño de tu mano como mascota', option1Votes: 0, option2: 'Llevar siempre un loro que repite todo lo que dices', option2Votes: 0 },
    { id: 75, option1: 'Olvidar los últimos 3 años de tu vida', option1Votes: 0, option2: 'Olvidar los próximos 3 años de tu vida', option2Votes: 0 },
    { id: 76, option1: 'Despertar con un nuevo color de pelo cada día', option1Votes: 0, option2: 'Despertar con una voz diferente cada mañana', option2Votes: 0 },
    { id: 77, option1: 'Tener un pato siguiéndote a todas partes', option1Votes: 0, option2: 'Tener que caminar como un pato a todas partes', option2Votes: 0 },
    { id: 78, option1: 'No tener cejas', option1Votes: 0, option2: 'No tener pestañas', option2Votes: 0 },
    { id: 79, option1: 'No tener familia', option1Votes: 0, option2: 'No tener amigos', option2Votes: 0 },
    { id: 80, option1: 'Estar siempre descalzo', option1Votes: 0, option2: 'No poder quitarte los zapatos', option2Votes: 0 },
    { id: 81, option1: 'Nunca tener hijos', option1Votes: 0, option2: 'Tener 10 hijos', option2Votes: 0 },
    { id: 82, option1: 'Que siempre te huelan los pies', option1Votes: 0, option2: 'Que siempre te huela la boca', option2Votes: 0 },
    { id: 83, option1: 'Que la temperatura siempre esté debajo de los 0 grados centígrados', option1Votes: 0, option2: 'Que la temperatura siempre esté por encima de los 30 grados centígrados', option2Votes: 0 },
    { id: 84, option1: 'Beber solo agua por el resto de tu vida', option1Votes: 0, option2: 'Beber solo leche por el resto de tu vida', option2Votes: 0 },
    { id: 85, option1: 'Siempre decir mentiras', option1Votes: 0, option2: 'Siempre decir la verdad', option2Votes: 0 },
    { id: 86, option1: 'Vivir estresado', option1Votes: 0, option2: 'Vivir aburrido', option2Votes: 0 },
    { id: 87, option1: 'Despertar todos los días con una pesadilla', option1Votes: 0, option2: 'Despertar todos los días sin recordar lo que sucedió el día anterior', option2Votes: 0 },
    { id: 88, option1: 'Golpear tu dedo meñique con un mueble todos los días', option1Votes: 0, option2: 'Morder tu lengua todos los días', option2Votes: 0 },
    { id: 89, option1: 'No poder aprender nada nuevo', option1Votes: 0, option2: 'Olvidar todo lo que aprendiste', option2Votes: 0 },
];
